import { useState } from "react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { LayoutDashboard, Package, ArrowLeftRight, ShoppingCart, Truck, TrendingUp, FileText, Store, LogOut, Menu, Plus, Bot, Users, Settings, ShieldCheck, WalletCards } from "lucide-react";
import { fmtNum } from "../lib/format";
import { useAuth } from "../context/AuthContext";
import AIAssistant from "./AIAssistant";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "./ui/sheet";
const RANK={vendedor:1,administrador:2,propietario:3};
const NAV=[{label:"Dashboard",path:"/dashboard",icon:LayoutDashboard,testid:"nav-dashboard",min:"vendedor"},{label:"Productos",path:"/productos",icon:Package,testid:"nav-productos",min:"vendedor"},{label:"Movimientos",path:"/movimientos",icon:ArrowLeftRight,testid:"nav-movimientos",min:"vendedor"},{label:"Ventas",path:"/ventas",icon:ShoppingCart,testid:"nav-ventas",min:"vendedor"},{label:"Compras",path:"/compras",icon:Truck,testid:"nav-compras",min:"administrador"},{label:"Finanzas",path:"/finanzas",icon:TrendingUp,testid:"nav-finanzas",min:"administrador"},{label:"Cuentas",path:"/cuentas",icon:WalletCards,testid:"nav-cuentas",min:"administrador"},{label:"Reportes",path:"/reportes",icon:FileText,testid:"nav-reportes",min:"administrador"},{label:"Equipo",path:"/equipo",icon:Users,testid:"nav-equipo",min:"propietario"},{label:"Configuración",path:"/configuracion",icon:Settings,testid:"nav-configuracion",min:"propietario"}];
function NavItems({onNavigate,mobile=false}){const {role,isSuper}=useAuth();const rank=RANK[role]??3;const items=NAV.filter(n=>rank>=RANK[n.min]);const all=isSuper?[...items,{label:"Plataforma",path:"/plataforma",icon:ShieldCheck,testid:"nav-plataforma"}]:items;return <nav className="flex-1 px-3 py-4 space-y-1">{all.map(item=><NavLink key={item.path} to={item.path} data-testid={mobile?`${item.testid}-mobile`:item.testid} onClick={onNavigate} className={({isActive})=>`flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-sm font-medium transition-colors ${isActive?"bg-white/10 text-white border-l-2 border-emerald-400":"text-slate-400 hover:text-white hover:bg-white/5"}`}><item.icon className="w-5 h-5 shrink-0"/>{item.label}</NavLink>)}</nav>}
function SidebarContent({onNavigate,mobile=false}){const {user,business,logout}=useAuth();const navigate=useNavigate();return <div className="flex flex-col h-full bg-[#0F172A]"><div className="px-5 py-5 flex items-center gap-3 border-b border-white/10"><div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center shrink-0"><Store className="w-5 h-5 text-white"/></div><div className="min-w-0"><p className="font-heading font-extrabold text-white text-base leading-tight">CuadrApp</p><p className="text-xs text-slate-400 truncate" data-testid="sidebar-business-name">{business?.name}</p></div></div><NavItems onNavigate={onNavigate} mobile={mobile}/><div className="p-4 border-t border-white/10"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-emerald-700 flex items-center justify-center text-white text-sm font-bold shrink-0">{(user?.name||"U")[0].toUpperCase()}</div><div className="flex-1 min-w-0"><p className="text-sm font-semibold text-white truncate">{user?.name}</p><p className="text-xs text-slate-400 truncate">{user?.email}</p></div><button data-testid="logout-btn" title="Cerrar sesión" onClick={async()=>{await logout();navigate("/auth");}} className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors"><LogOut className="w-4 h-4"/></button></div></div></div>}
export default function Layout(){const {business,rate,isAdmin}=useAuth();const [aiOpen,setAiOpen]=useState(false);const [menuOpen,setMenuOpen]=useState(false);return <div className="min-h-screen bg-background"><aside className="hidden lg:block fixed inset-y-0 left-0 w-64 z-40"><SidebarContent/></aside><div className="lg:pl-64 flex flex-col min-h-screen"><header className="sticky top-0 z-30 bg-background/85 backdrop-blur-md border-b border-border"><div className="px-4 sm:px-6 lg:px-8 h-16 flex items-center gap-3"><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button data-testid="mobile-menu-btn" className="lg:hidden p-2 rounded-lg hover:bg-secondary"><Menu className="w-5 h-5"/></button></SheetTrigger><SheetContent side="left" aria-describedby={undefined} className="p-0 w-64 border-0"><SheetTitle className="sr-only">Menú de navegación</SheetTitle><SidebarContent mobile onNavigate={()=>setMenuOpen(false)}/></SheetContent></Sheet><div className="flex-1 min-w-0"><p className="font-heading font-bold text-slate-900 truncate" data-testid="header-business-name">{business?.name}</p><p className="text-xs text-muted-foreground">Moneda: {business?.currency||"USD"}</p></div>{rate?.rate&&<span data-testid="header-bcv-rate" className="hidden md:inline-flex items-center gap-1.5 text-xs font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200 px-3 py-1.5 rounded-full">1 USD = Bs {fmtNum(rate.rate)}</span>}<button data-testid="ai-assistant-launcher" onClick={()=>setAiOpen(true)} className="hidden sm:flex items-center gap-2 text-xs font-semibold bg-slate-900 text-white px-3.5 py-2 rounded-full"><Bot className="w-3.5 h-3.5"/> Preguntar a Pyme</button>{isAdmin&&<Link to="/compras?nueva=1" data-testid="quick-add-purchase-btn" className="hidden sm:flex items-center gap-1.5 text-xs font-semibold border border-border bg-card px-3.5 py-2 rounded-full"><Plus className="w-3.5 h-3.5"/> Compra</Link>}<Link to="/ventas?nueva=1" data-testid="quick-add-sale-btn" className="flex items-center gap-1.5 text-xs font-semibold bg-primary text-white px-3.5 py-2 rounded-full"><Plus className="w-3.5 h-3.5"/> Venta</Link></div></header><main className="flex-1 px-4 sm:px-6 lg:px-8 py-6 max-w-7xl w-full mx-auto"><Outlet/></main></div>{!aiOpen&&<button data-testid="ai-assistant-fab" onClick={()=>setAiOpen(true)} className="fixed bottom-5 right-5 z-40 w-14 h-14 rounded-full bg-slate-900 text-white shadow-xl flex items-center justify-center"><Bot className="w-6 h-6"/></button>}<AIAssistant open={aiOpen} onClose={()=>setAiOpen(false)}/></div>}
