import { useEffect, useState } from "react";
import { Check, Clock3, Eye, Image as ImageIcon, X } from "lucide-react";
import { toast } from "sonner";
import api, { apiError } from "../lib/api";
import { Button } from "./ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "./ui/dialog";
import { fmtDate, fmtMoney, fmtNum } from "../lib/format";

export default function PendingPayments() {
  const [payments, setPayments] = useState([]), [selected, setSelected] = useState(null), [busy, setBusy] = useState(null);
  const load = async () => { try { const r = await api.get("/platform/billing?status=pendiente_verificacion"); setPayments(r.data.billing || []); } catch (e) { toast.error(apiError(e)); } };
  useEffect(() => { load(); const id = setInterval(load, 30000); return () => clearInterval(id); }, []);
  const verify = async (id, approved) => { setBusy(id); try { await api.patch(`/platform/billing/${id}/verify?approved=${approved}`); toast.success(approved ? "Pago aprobado y suscripción actualizada" : "Pago rechazado"); setSelected(null); load(); } catch (e) { toast.error(apiError(e)); } finally { setBusy(null); } };
  return <>{payments.length > 0 && <button type="button" onClick={load} className="fixed right-5 bottom-24 z-40 flex items-center gap-2 rounded-full border bg-card px-4 py-2.5 text-sm font-bold shadow-xl"><Clock3 className="w-4 h-4 text-amber-600"/>Pagos pendientes <span className="rounded-full bg-amber-500 px-2 py-0.5 text-xs text-white">{payments.length}</span></button>}
    <Dialog open={selected !== null} onOpenChange={v => !v && setSelected(null)}><DialogContent className="max-w-3xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>Comprobante de pago</DialogTitle></DialogHeader>{selected && <div className="space-y-4"><div className="grid sm:grid-cols-2 gap-3 text-sm"><div><span className="text-muted-foreground">Negocio</span><p className="font-semibold">{selected.business_id}</p></div><div><span className="text-muted-foreground">Método</span><p className="font-semibold">{selected.payment_method}</p></div><div><span className="text-muted-foreground">Monto</span><p className="font-semibold">{fmtMoney(selected.amount_usd || selected.amount,"USD")} · Bs {fmtNum(selected.amount_bs || 0)}</p></div><div><span className="text-muted-foreground">Fecha</span><p className="font-semibold">{fmtDate(selected.paid_at)}</p></div><div><span className="text-muted-foreground">Referencia</span><p className="font-semibold">{selected.reference || "Sin referencia"}</p></div></div><div className="rounded-xl border bg-secondary/30 p-3"><div className="flex items-center gap-2 mb-2 text-sm font-semibold"><ImageIcon className="w-4 h-4"/>Comprobante</div><img src={selected.receipt_image} alt="Comprobante de pago" className="max-h-[55vh] w-full object-contain rounded-lg bg-background"/></div><div className="flex justify-end gap-2"><Button variant="outline" disabled={busy===selected.id} onClick={() => verify(selected.id,false)}><X className="w-4 h-4 mr-1"/>Rechazar</Button><Button disabled={busy===selected.id} onClick={() => verify(selected.id,true)}><Check className="w-4 h-4 mr-1"/>{busy===selected.id?"Procesando…":"Aprobar pago"}</Button></div></div>}</DialogContent></Dialog>
    {payments.length > 0 && <div className="fixed inset-x-0 bottom-0 z-30 bg-card/95 backdrop-blur border-t p-3 lg:pl-72"><div className="max-w-7xl mx-auto flex items-center gap-3 overflow-x-auto"><b className="text-sm whitespace-nowrap">Pagos por verificar:</b>{payments.slice(0,5).map(p=><button key={p.id} type="button" onClick={() => setSelected(p)} className="shrink-0 flex items-center gap-2 rounded-lg border px-3 py-2 text-xs hover:bg-muted"><Eye className="w-3.5 h-3.5"/>{p.business_id.slice(0,12)} · {fmtMoney(p.amount_usd || p.amount,"USD")}</button>)}{payments.length>5&&<span className="text-xs text-muted-foreground">+{payments.length-5} más</span>}</div></div>}
  </>;
}
