import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { CheckCircle2, Clock3 } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { apiError } from "../lib/api";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";

const VALUE_PROPS=["Controla tu inventario sin ser experto","Sabe qué productos te dejan más ganancia","Recibe alertas antes de quedarte sin stock","Consulta a Cubi sobre tu negocio"];
export default function AuthPage(){
 const {login,register}=useAuth(); const navigate=useNavigate(); const [error,setError]=useState(""); const [pending,setPending]=useState(false); const [loading,setLoading]=useState(false);
 const [loginForm,setLoginForm]=useState({email:"",password:""}); const [regForm,setRegForm]=useState({name:"",email:"",password:"",confirm:""});
 const go=data=>navigate(data.business?"/dashboard":"/onboarding",{replace:true});
 const doLogin=async e=>{e.preventDefault();setError("");setLoading(true);try{go(await login(loginForm.email,loginForm.password));}catch(err){setError(apiError(err,"No pudimos iniciar sesión."));}finally{setLoading(false);}};
 const doRegister=async e=>{e.preventDefault();setError("");if(regForm.password!==regForm.confirm){setError("Las contraseñas no coinciden.");return;}setLoading(true);try{const data=await register(regForm.name,regForm.email,regForm.password);if(data.pending_approval){setPending(true);return;}go(data);}catch(err){setError(apiError(err,"No pudimos crear tu cuenta."));}finally{setLoading(false);}};
 return <div className="min-h-screen grid lg:grid-cols-2 bg-background">
  <div className="hidden lg:flex relative flex-col justify-between p-10 bg-[#123A2B] text-white overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary/40 via-transparent to-black/10"/><div className="relative flex items-center gap-4"><img src="/cuadrapp-logo.svg" className="w-14 h-14 rounded-2xl" alt="CuadraApp"/><span className="font-heading font-extrabold text-3xl tracking-tight">CuadraApp</span></div><div className="relative space-y-6"><h1 className="font-heading text-4xl xl:text-5xl font-extrabold leading-tight tracking-tight">Entiende tu negocio<br/>en un vistazo.</h1><p className="text-slate-200 text-lg max-w-md">Inventario, ventas, compras y finanzas en un solo lugar. Simple para ti, profesional por dentro.</p><ul className="space-y-3">{VALUE_PROPS.map(v=><li key={v} className="flex items-center gap-3 text-sm text-slate-100"><CheckCircle2 className="w-5 h-5 text-emerald-300 shrink-0"/>{v}</li>)}</ul></div><p className="relative text-xs text-slate-300/70">Hecho para tiendas, bodegas, ferreterías, papelerías y emprendimientos.</p></div>
  <div className="flex items-center justify-center p-6"><div className="w-full max-w-md"><div className="lg:hidden flex flex-col items-center gap-2 mb-8"><img src="/cuadrapp-logo.svg" className="w-14 h-14 rounded-2xl" alt="CuadraApp"/><span className="font-heading font-extrabold text-3xl tracking-tight">CuadraApp</span></div>
   {pending?<div className="text-center space-y-5 bg-card border border-border rounded-3xl p-8"><div className="w-16 h-16 rounded-full bg-amber-100 flex items-center justify-center mx-auto"><Clock3 className="w-8 h-8 text-amber-600"/></div><h1 className="font-heading text-2xl font-extrabold">Solicitud recibida</h1><p className="text-sm text-muted-foreground">Tu cuenta fue creada correctamente, pero necesita aprobación antes de ingresar a CuadraApp.</p><p className="text-sm text-muted-foreground">Cuando sea aprobada podrás iniciar sesión con tu correo y contraseña.</p><Button variant="outline" className="rounded-xl" onClick={()=>setPending(false)}>Volver a iniciar sesión</Button></div>:<Tabs defaultValue="login" className="w-full"><TabsList className="grid grid-cols-2 w-full mb-6"><TabsTrigger value="login">Iniciar sesión</TabsTrigger><TabsTrigger value="register">Crear cuenta</TabsTrigger></TabsList>{error&&<div className="mb-4 text-sm bg-rose-50 border border-rose-200 text-rose-700 rounded-xl px-4 py-3">{error}</div>}<TabsContent value="login"><form onSubmit={doLogin} className="space-y-4"><div className="space-y-1.5"><Label>Correo electrónico</Label><Input type="email" required placeholder="tucorreo@ejemplo.com" value={loginForm.email} onChange={e=>setLoginForm({...loginForm,email:e.target.value})}/></div><div className="space-y-1.5"><Label>Contraseña</Label><Input type="password" required placeholder="••••••••" value={loginForm.password} onChange={e=>setLoginForm({...loginForm,password:e.target.value})}/></div><Button type="submit" disabled={loading} className="w-full rounded-xl h-11 font-semibold">{loading?"Entrando…":"Entrar a mi negocio"}</Button></form></TabsContent><TabsContent value="register"><form onSubmit={doRegister} className="space-y-4"><div className="space-y-1.5"><Label>Tu nombre</Label><Input required placeholder="Ej. María Pérez" value={regForm.name} onChange={e=>setRegForm({...regForm,name:e.target.value})}/></div><div className="space-y-1.5"><Label>Correo electrónico</Label><Input type="email" required placeholder="tucorreo@ejemplo.com" value={regForm.email} onChange={e=>setRegForm({...regForm,email:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-1.5"><Label>Contraseña</Label><Input type="password" required minLength={8} placeholder="Mín. 8 caracteres" value={regForm.password} onChange={e=>setRegForm({...regForm,password:e.target.value})}/></div><div className="space-y-1.5"><Label>Confirmar</Label><Input type="password" required placeholder="Repite la contraseña" value={regForm.confirm} onChange={e=>setRegForm({...regForm,confirm:e.target.value})}/></div></div><Button type="submit" disabled={loading} className="w-full rounded-xl h-11 font-semibold">{loading?"Enviando solicitud…":"Solicitar acceso"}</Button><p className="text-xs text-muted-foreground text-center">Tu registro será revisado antes de permitir el acceso.</p></form></TabsContent></Tabs>}
  </div></div></div>;
}
