import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Download, Eye, Plus, Trash2, Truck, X } from "lucide-react";
import { toast } from "sonner";
import api, { apiError, downloadCsv } from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { fmtDateTime, fmtMoney, fmtNum, PAYMENT_METHODS } from "../lib/format";
import ProductCombobox from "../components/ProductCombobox";
import FacturaModal from "../components/Factura";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "../components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../components/ui/select";

const emptyItem=()=>({product_id:"",quantity:"1",unit_cost:""});
const emptyPart=(method="efectivo")=>({method,amount:""});
const FOREIGN=new Set(["divisas","tarjeta_divisa","zelle"]);

export default function Compras(){
 const{business}=useAuth();const currency=business?.currency||"USD";const[params,setParams]=useSearchParams();
 const[purchases,setPurchases]=useState(null);const[products,setProducts]=useState([]);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[items,setItems]=useState([emptyItem()]);
 const[supplier,setSupplier]=useState("");const[supplierRif,setSupplierRif]=useState("");const[payment,setPayment]=useState("efectivo");const[combined,setCombined]=useState(false);const[paymentParts,setPaymentParts]=useState([emptyPart("efectivo"),emptyPart("tarjeta")]);const[facturaDoc,setFacturaDoc]=useState(null);
 const load=useCallback(()=>{api.get("/purchases").then(r=>setPurchases(r.data.purchases)).catch(e=>toast.error(apiError(e)));},[]);useEffect(()=>{load();},[load]);useEffect(()=>{api.get("/products").then(r=>setProducts(r.data.products)).catch(()=>{});},[]);useEffect(()=>{if(params.get("nueva")==="1"){setOpen(true);setParams({}, {replace:true});}},[params,setParams]);
 const setItem=(i,patch)=>setItems(items.map((it,j)=>j===i?{...it,...patch}:it));
 const addProductLine=prod=>{const idx=items.findIndex(it=>it.product_id===prod.id);if(idx>=0)setItem(idx,{quantity:String((Number(items[idx].quantity)||0)+1)});else{const line={product_id:prod.id,quantity:"1",unit_cost:String(prod.purchase_price)};const empt=items.findIndex(it=>!it.product_id);if(empt>=0)setItem(empt,line);else setItems([...items,line]);}};
 const base=items.reduce((acc,it)=>acc+(Number(it.unit_cost)||0)*(Number(it.quantity)||0),0);
 const paymentTarget=useMemo(()=>{const iva=business?.iva_enabled?base*Number(business?.iva_percent||16)/100:0;const delivery=business?.delivery_enabled?Number(business?.delivery_amount||0):0;const before=base+iva+delivery;const rate=Number(business?.igtf_percent||3)/100;const foreign=combined?paymentParts.filter(p=>FOREIGN.has(p.method)).reduce((s,p)=>s+(Number(p.amount)||0),0):(FOREIGN.has(payment)?before:0);return before+(business?.igtf_enabled?foreign*rate:0);},[base,business,combined,paymentParts,payment]);
 const paid=paymentParts.reduce((s,p)=>s+(Number(p.amount)||0),0);const difference=Number((paymentTarget-paid).toFixed(2));
 const save=async e=>{e.preventDefault();setSaving(true);try{const payload={supplier:supplier||null,supplier_rif:supplierRif||null,items:items.map(it=>({product_id:it.product_id,quantity:Number(it.quantity),unit_cost:Number(it.unit_cost)||0})),payment_method:combined?"combinado":payment,payment_parts:combined?paymentParts.filter(p=>Number(p.amount)>0).map(p=>({method:p.method,amount:Number(p.amount)})):[]};const{data}=await api.post("/purchases",payload);toast.success(`Compra ${data.purchase.invoice_number||""} registrada por ${fmtMoney(data.purchase.total,currency)}. Tu stock ya fue actualizado.`);setOpen(false);setItems([emptyItem()]);setSupplier("");setSupplierRif("");setCombined(false);setPaymentParts([emptyPart("efectivo"),emptyPart("tarjeta")]);setFacturaDoc(data.purchase);load();api.get("/products").then(r=>setProducts(r.data.products)).catch(()=>{});}catch(err){toast.error(apiError(err));}finally{setSaving(false);}};
 return <div className="space-y-5" data-testid="compras-page"><div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="font-heading text-3xl font-extrabold tracking-tight text-slate-900">Compras</h1><p className="text-sm text-muted-foreground mt-1">Cada compra suma inventario y actualiza el costo del producto.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>downloadCsv("/purchases/export/csv","compras.csv")} className="rounded-xl"><Download className="w-4 h-4 mr-1.5"/>Exportar CSV</Button><Button onClick={()=>setOpen(true)} className="rounded-xl"><Plus className="w-4 h-4 mr-1.5"/>Registrar compra</Button></div></div>
 <div className="bg-card border border-border rounded-2xl overflow-hidden">{!purchases?<div className="p-6 space-y-3">{[...Array(5)].map((_,i)=><div key={i} className="h-10 bg-secondary rounded-xl animate-pulse"/>)}</div>:purchases.length===0?<div className="p-12 text-center"><Truck className="w-10 h-10 text-muted-foreground mx-auto mb-3"/><p className="font-semibold text-slate-800">Aún no registras compras</p><p className="text-sm text-muted-foreground mt-1 mb-4">Cuando compres mercancía, regístrala aquí.</p><Button onClick={()=>setOpen(true)} className="rounded-xl"><Plus className="w-4 h-4 mr-1.5"/>Registrar compra</Button></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wide text-muted-foreground border-b border-border bg-secondary/50"><th className="px-5 py-3">Fecha</th><th className="px-4 py-3">Comprobante</th><th className="px-4 py-3">Proveedor</th><th className="px-4 py-3">Productos</th><th className="px-4 py-3">Pago</th><th className="px-4 py-3 text-right">Total</th><th/></tr></thead><tbody className="divide-y divide-border">{purchases.map(p=><tr key={p.id} className="hover:bg-secondary/40"><td className="px-5 py-3 text-muted-foreground whitespace-nowrap">{fmtDateTime(p.created_at)}</td><td className="px-4 py-3 font-num text-xs font-semibold">{p.invoice_number||"—"}</td><td className="px-4 py-3 font-medium">{p.supplier||"—"}</td><td className="px-4 py-3 max-w-md"><span className="line-clamp-1">{p.items.map(i=>`${i.name} x${fmtNum(i.quantity)}`).join(", ")}</span></td><td className="px-4 py-3"><span className="text-xs bg-secondary px-2 py-0.5 rounded-full capitalize">{p.payment_method}</span></td><td className="px-4 py-3 text-right font-num font-semibold">{fmtMoney(p.total,currency)}</td><td className="px-4 py-3 text-right"><button title="Ver comprobante" onClick={()=>setFacturaDoc(p)}><Eye className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>}</div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent aria-describedby={undefined} className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle className="font-heading">Registrar compra</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div><Label className="text-xs mb-1.5 block">Escanear o buscar producto</Label><ProductCombobox products={products} currency={currency} placeholder="Escanea el código de barras o escribe el nombre…" onSelect={addProductLine}/></div>
 <div className="grid grid-cols-2 gap-3"><div className="space-y-1.5"><Label>Proveedor</Label><Input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Ej. Distribuidora López"/></div><div className="space-y-1.5"><Label>RIF del proveedor</Label><Input value={supplierRif} onChange={e=>setSupplierRif(e.target.value)} placeholder="J-12345678-9"/></div><div className="space-y-1.5"><Label>Método de pago</Label><Select value={payment} onValueChange={v=>{setPayment(v);setCombined(false)}} disabled={combined}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{PAYMENT_METHODS.map(m=><SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button type="button" variant={combined?"default":"outline"} className="w-full" onClick={()=>setCombined(v=>!v)}>{combined?"Pago combinado activo":"Dividir el pago"}</Button></div></div>
 <div className="space-y-3">{items.map((it,i)=>{const sel=products.find(x=>x.id===it.product_id);return <div key={i} className="grid grid-cols-12 gap-2 items-end bg-secondary/50 rounded-xl p-3"><div className="col-span-12 sm:col-span-6 space-y-1"><Label className="text-xs">Producto</Label>{sel?<div className="flex items-center gap-2 bg-card border border-border rounded-lg px-2.5 py-2"><span className="text-sm flex-1 truncate font-medium">{sel.name}</span><button type="button" onClick={()=>setItem(i,{product_id:""})}><X className="w-3.5 h-3.5"/></button></div>:<ProductCombobox products={products} currency={currency} placeholder="Buscar producto…" onSelect={prod=>setItem(i,{product_id:prod.id,unit_cost:String(prod.purchase_price)})}/>}</div><div className="col-span-5 sm:col-span-2 space-y-1"><Label className="text-xs">Cantidad</Label><Input type="number" min="0.01" step="any" required value={it.quantity} onChange={e=>setItem(i,{quantity:e.target.value})}/></div><div className="col-span-5 sm:col-span-3 space-y-1"><Label className="text-xs">Costo unitario</Label><Input type="number" min="0" step="any" required value={it.unit_cost} onChange={e=>setItem(i,{unit_cost:e.target.value})}/></div><div className="col-span-2 sm:col-span-1"><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==i))}><Trash2 className="w-4 h-4"/></button></div></div>})}<Button type="button" variant="outline" size="sm" onClick={()=>setItems([...items,emptyItem()])} className="rounded-xl"><Plus className="w-3.5 h-3.5 mr-1"/>Agregar otro producto</Button></div>
 {combined&&<div className="border border-primary/20 bg-primary/5 rounded-xl p-4 space-y-3"><div className="flex justify-between"><div><p className="font-semibold text-sm">Pago dividido</p><p className="text-xs text-muted-foreground">Puedes combinar efectivo, tarjeta, transferencia o divisas.</p></div><span className={`text-xs font-semibold ${Math.abs(difference)<=0.01?"text-emerald-700":"text-amber-700"}`}>{Math.abs(difference)<=0.01?"Completo":`Faltan ${fmtMoney(Math.max(difference,0),currency)}`}</span></div>{paymentParts.map((part,i)=><div key={i} className="grid grid-cols-2 gap-2"><Select value={part.method} onValueChange=v=>setPaymentParts(paymentParts.map((p,j)=>j===i?{...p,method:v}:p))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{PAYMENT_METHODS.map(m=><SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" step="0.01" value={part.amount} onChange={e=>setPaymentParts(paymentParts.map((p,j)=>j===i?{...p,amount:e.target.value}:p))} placeholder="Monto"/></div>)}<Button type="button" variant="ghost" size="sm" onClick={()=>setPaymentParts([...paymentParts,emptyPart()])}>+ Agregar otro método</Button><p className="text-xs text-muted-foreground">Total estimado con cargos configurados: <strong>{fmtMoney(paymentTarget,currency)}</strong> · Registrado: <strong>{fmtMoney(paid,currency)}</strong></p></div>}
 <div className="bg-secondary/60 rounded-xl p-4 flex justify-between items-center"><span className="font-heading font-extrabold text-lg">Total base</span><span className="font-num font-extrabold text-lg">{fmtMoney(base,currency)}</span></div><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving||items.some(it=>!it.product_id)||(combined&&Math.abs(difference)>0.01)} className="rounded-xl">{saving?"Registrando…":"Registrar compra"}</Button></div></form></DialogContent></Dialog>
 <FacturaModal open={!!facturaDoc} onClose={()=>setFacturaDoc(null)} kind="compra" doc={facturaDoc} business={business}/>
 </div>;
}
