import {useCallback,useEffect,useState} from "react";
import {BrainCircuit,RefreshCw,TrendingUp,TrendingDown,Package,AlertTriangle,BarChart3,ShoppingCart,MessageCircle,ShieldAlert,Lightbulb} from "lucide-react";
import {toast} from "sonner";import api,{apiError} from "../lib/api";import {fmtMoney,fmtNum} from "../lib/format";import {useAuth} from "../context/AuthContext";

export default function Cubi(){
 const{business,entitlements}=useAuth();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/cubi/insights");setData(r.data)}catch(e){toast.error(apiError(e,"No pudimos cargar la inteligencia de Cubi."))}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const currency=business?.currency||"USD";const forecast=data?.forecast||{};const inventory=data?.inventory_recommendations||[];const abc=data?.abc_analysis||[];const anomaly=data?.anomaly||{};const analysis=data?.analysis||{};const summary=data?.summary||{};const health=data?.health_score||{};const chatLimit=entitlements?.cubi_chat_limit||10;const cubiLevel=entitlements?.cubi||"basic";
 const confidenceLabel={high:"Alta",medium:"Media",low:"Baja"}[analysis.confidence]||"Media";
 if(loading&&!data)return <div className="space-y-4"><div className="h-10 w-72 bg-secondary rounded-xl animate-pulse"/><div className="grid md:grid-cols-4 gap-4">{[1,2,3,4].map(x=><div key={x} className="h-28 bg-card border rounded-2xl animate-pulse"/>)}</div></div>;
 return <div className="space-y-5" data-testid="cubi-page">
  <div className="flex items-center justify-between gap-3 flex-wrap"><div><h1 className="font-heading text-3xl font-extrabold flex items-center gap-2"><BrainCircuit className="w-7 h-7 text-primary"/>Cubi Inteligencia</h1><p className="text-sm text-muted-foreground mt-1">Tu asesor de negocio: analiza los datos, explica qué significan y te ayuda a decidir.</p></div><button onClick={load} disabled={loading} className="h-10 px-4 rounded-xl border bg-card flex items-center gap-2 text-sm font-semibold"><RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`}/>Actualizar</button></div>
  <div className="rounded-2xl border bg-primary/5 p-5"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center"><BrainCircuit className="w-6 h-6 text-primary"/></div><div><p className="font-heading font-bold">Cubi piensa como un experto y habla sencillo</p><p className="text-sm text-muted-foreground">Motor financiero + Business Intelligence · nivel {cubiLevel} · {data?.history?.sales_count||0} ventas analizadas.</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><MessageCircle className="w-4 h-4"/>Chat de Cubi: hasta {chatLimit} consultas diarias en tu plan.</div></div>
  <div className="grid lg:grid-cols-5 gap-4">
   <div className="bg-card border rounded-2xl p-4 lg:col-span-1"><p className="text-xs text-muted-foreground">Salud del negocio</p><p className="font-heading text-3xl font-extrabold mt-1">{health.score!==undefined?`${fmtNum(health.score)}/100`:"—"}</p><p className="text-xs text-muted-foreground mt-1">Lectura basada en margen, crecimiento, gastos e inventario.</p></div>
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Ventas 30 días</p><p className="font-heading text-2xl font-extrabold mt-1">{fmtMoney(summary.revenue_current_30d||0,currency)}</p><p className="text-xs mt-1 flex items-center gap-1">{summary.revenue_growth_percent>=0?<TrendingUp className="w-3.5 h-3.5 text-emerald-600"/>:<TrendingDown className="w-3.5 h-3.5 text-rose-600"/>}{summary.revenue_growth_percent!==null&&summary.revenue_growth_percent!==undefined?`${summary.revenue_growth_percent>=0?"+":""}${fmtNum(summary.revenue_growth_percent)}% vs. período anterior`:"Sin comparación"}</p></div>
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Margen estimado</p><p className="font-heading text-2xl font-extrabold mt-1">{fmtNum(summary.margin_percent||0)}%</p><p className="text-xs text-muted-foreground mt-1">Después del costo del producto.</p></div>
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Ticket promedio</p><p className="font-heading text-2xl font-extrabold mt-1">{fmtMoney(summary.average_ticket||0,currency)}</p><p className="text-xs text-muted-foreground mt-1">Promedio por venta.</p></div>
   <div className={`border rounded-2xl p-4 ${anomaly.is_anomaly?"bg-amber-50 border-amber-200":"bg-emerald-50 border-emerald-200"}`}><p className="text-xs text-muted-foreground">Comportamiento</p><p className="font-heading text-xl font-extrabold mt-1">{anomaly.is_anomaly?"Atención":"Estable"}</p><p className="text-xs mt-1">{anomaly.is_anomaly?anomaly.message||"Hay una variación que conviene revisar.":"No detectamos una anomalía reciente."}</p></div>
  </div>
  <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><BrainCircuit className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Lectura de Cubi</h2><p className="text-xs text-muted-foreground">Primero los datos. Después la interpretación. Nunca inventa una certeza.</p></div></div><div className="grid lg:grid-cols-3 gap-3"><div className="rounded-xl bg-secondary/60 p-4"><p className="font-semibold text-sm">Qué veo</p><div className="mt-2 space-y-1">{(analysis.facts||[]).slice(0,3).map((x,i)=><p key={i} className="text-sm text-muted-foreground">• {x}</p>)}</div></div><div className="rounded-xl bg-amber-50 p-4"><p className="font-semibold text-sm flex items-center gap-2"><ShieldAlert className="w-4 h-4"/>Qué me preocupa</p><div className="mt-2 space-y-1">{(analysis.risks||[]).slice(0,3).map((x,i)=><p key={i} className="text-sm text-muted-foreground">• {x}</p>)}{!(analysis.risks||[]).length&&<p className="text-sm text-muted-foreground">No veo un riesgo prioritario con los datos actuales.</p>}</div></div><div className="rounded-xl bg-primary/5 p-4"><p className="font-semibold text-sm flex items-center gap-2"><Lightbulb className="w-4 h-4"/>Qué haría</p><div className="mt-2 space-y-1">{(analysis.recommendations||[]).slice(0,3).map((x,i)=><p key={i} className="text-sm text-muted-foreground">• {x}</p>)}{!(analysis.recommendations||[]).length&&<p className="text-sm text-muted-foreground">Seguir observando la evolución antes de tomar una decisión.</p>}</div></div></div><div className="mt-4 flex items-center justify-between gap-3 flex-wrap text-xs text-muted-foreground"><span>Confianza de esta lectura: <strong>{confidenceLabel}</strong></span><span>La confianza indica qué tan completos son los datos; no significa certeza sobre las causas.</span></div></section>
  <div className="grid lg:grid-cols-2 gap-5">
   <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Package className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Qué debes reponer</h2><p className="text-xs text-muted-foreground">Prioridad por días estimados hasta agotarse.</p></div></div>{inventory.length===0?<p className="text-sm text-muted-foreground">No hay reposiciones sugeridas con los datos actuales.</p>:<div className="space-y-2">{inventory.slice(0,8).map(p=><div key={p.product_id} className="flex items-center gap-3 border rounded-xl p-3"><div className={`w-2.5 h-2.5 rounded-full ${p.estimated_days_to_stockout!==null&&p.estimated_days_to_stockout<=3?"bg-rose-500":"bg-amber-400"}`}/><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{p.product_name}</p><p className="text-xs text-muted-foreground">Stock {fmtNum(p.stock)} · demanda {fmtNum(p.daily_demand)}/día</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Comprar</p><p className="font-bold">{fmtNum(p.suggested_purchase)}</p></div></div>)}</div>}</section>
   <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><BarChart3 className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Productos que mueven tu negocio</h2><p className="text-xs text-muted-foreground">Clasificación ABC por facturación.</p></div></div>{abc.length===0?<p className="text-sm text-muted-foreground">Aún no hay ventas suficientes.</p>:<div className="space-y-2">{abc.slice(0,8).map(p=><div key={p.product_id} className="flex items-center gap-3 border rounded-xl p-3"><span className={`w-8 h-8 rounded-lg flex items-center justify-center font-extrabold text-sm ${p.abc_class==="A"?"bg-primary/10 text-primary":p.abc_class==="B"?"bg-amber-100 text-amber-700":"bg-secondary text-muted-foreground"}`}>{p.abc_class}</span><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{p.product_name}</p><p className="text-xs text-muted-foreground">{fmtNum(p.units)} uds · margen {fmtNum(p.margin_percent)}%</p></div><div className="text-right"><p className="font-bold">{fmtMoney(p.revenue,currency)}</p><p className="text-xs text-muted-foreground">utilidad {fmtMoney(p.profit,currency)}</p></div></div>)}</div>}</section>
  </div>
  <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ShoppingCart className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Proyección</h2><p className="text-xs text-muted-foreground">Una estimación de tendencia, no una promesa.</p></div></div>{forecast.available?<div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">Promedio diario reciente</p><p className="font-heading text-xl font-extrabold mt-1">{fmtMoney(forecast.recent_daily_average,currency)}</p></div><div className="rounded-xl bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">Estimación diaria</p><p className="font-heading text-xl font-extrabold mt-1">{fmtMoney(forecast.predicted_daily_revenue,currency)}</p></div><div className="rounded-xl bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">Próximos {forecast.horizon_days} días</p><p className="font-heading text-xl font-extrabold mt-1">{fmtMoney(forecast.predicted_period_revenue,currency)}</p></div></div>:<p className="text-sm text-muted-foreground">Necesitamos más historial para proyectar ventas con una base mínima.</p>}</section>
  {analysis.teaching?.length>0&&<section className="bg-card border rounded-2xl p-5"><h2 className="font-heading font-bold">Cubi también te enseña</h2><p className="text-xs text-muted-foreground mt-1">Cuando un concepto puede ayudarte a entender mejor el negocio, te lo explica sin complicarlo.</p><div className="grid md:grid-cols-2 gap-3 mt-4">{analysis.teaching.slice(0,2).map((x,i)=><div key={i} className="border rounded-xl p-4"><p className="font-semibold text-sm">{x.term}</p><p className="text-sm text-muted-foreground mt-1">{x.meaning}</p></div>)}</div></section>}
  {data?.history?.observed_days<7&&<div className="text-xs text-muted-foreground flex items-center gap-2"><AlertTriangle className="w-4 h-4"/>Cubi necesita al menos 7 días con ventas para generar un pronóstico confiable.</div>}
 </div>;
}
