import {useCallback,useEffect,useState} from "react";
import {BrainCircuit,RefreshCw,TrendingUp,TrendingDown,Package,AlertTriangle,BarChart3,ShoppingCart,MessageCircle} from "lucide-react";
import {toast} from "sonner";import api,{apiError} from "../lib/api";import {fmtMoney,fmtNum} from "../lib/format";import {useAuth} from "../context/AuthContext";

export default function Cubi(){
 const{business,entitlements}=useAuth();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/cubi/insights");setData(r.data)}catch(e){toast.error(apiError(e,"No pudimos cargar la inteligencia de Cubi."))}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const currency=business?.currency||"USD";const forecast=data?.forecast||{};const inventory=data?.inventory_recommendations||[];const abc=data?.abc_analysis||[];const anomaly=data?.anomaly||{};const chatLimit=entitlements?.cubi_chat_limit||10;const cubiLevel=entitlements?.cubi||"basic";
 if(loading&&!data)return <div className="space-y-4"><div className="h-10 w-72 bg-secondary rounded-xl animate-pulse"/><div className="grid md:grid-cols-4 gap-4">{[1,2,3,4].map(x=><div key={x} className="h-28 bg-card border rounded-2xl animate-pulse"/>)}</div></div>;
 return <div className="space-y-5" data-testid="cubi-page">
  <div className="flex items-center justify-between gap-3 flex-wrap"><div><h1 className="font-heading text-3xl font-extrabold flex items-center gap-2"><BrainCircuit className="w-7 h-7 text-primary"/>Cubi Inteligencia</h1><p className="text-sm text-muted-foreground mt-1">Análisis automático de tu negocio basado en tus propias ventas, productos y stock.</p></div><button onClick={load} disabled={loading} className="h-10 px-4 rounded-xl border bg-card flex items-center gap-2 text-sm font-semibold"><RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`}/>Actualizar</button></div>
  <div className="rounded-2xl border bg-primary/5 p-5"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center"><BrainCircuit className="w-6 h-6 text-primary"/></div><div><p className="font-heading font-bold">Cubi está aprendiendo de tu operación</p><p className="text-sm text-muted-foreground">Motor nativo · nivel {cubiLevel} · {data?.history?.sales_count||0} ventas analizadas.</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><MessageCircle className="w-4 h-4"/>Chat de Cubi: hasta {chatLimit} consultas diarias en tu plan.</div></div>
  <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Pronóstico diario</p><p className="font-heading text-2xl font-extrabold mt-1">{forecast.available?fmtMoney(forecast.predicted_daily_revenue,currency):"—"}</p><p className="text-xs text-muted-foreground mt-1">Próximos {forecast.horizon_days||7} días</p></div>
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Pronóstico del período</p><p className="font-heading text-2xl font-extrabold mt-1">{forecast.available?fmtMoney(forecast.predicted_period_revenue,currency):"—"}</p><p className="text-xs mt-1 flex items-center gap-1">{forecast.trend_percent>=0?<TrendingUp className="w-3.5 h-3.5 text-emerald-600"/>:<TrendingDown className="w-3.5 h-3.5 text-rose-600"/>}{forecast.available?`${forecast.trend_percent>=0?"+":""}${fmtNum(forecast.trend_percent)}% tendencia`:"Historial insuficiente"}</p></div>
   <div className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">Productos a reponer</p><p className="font-heading text-2xl font-extrabold mt-1">{fmtNum(inventory.length)}</p><p className="text-xs text-muted-foreground mt-1">Según demanda observada</p></div>
   <div className={`border rounded-2xl p-4 ${anomaly.is_anomaly?"bg-amber-50 border-amber-200":"bg-emerald-50 border-emerald-200"}`}><p className="text-xs text-muted-foreground">Comportamiento de ventas</p><p className="font-heading text-xl font-extrabold mt-1">{anomaly.is_anomaly?"Atención":"Estable"}</p><p className="text-xs mt-1">{anomaly.is_anomaly?anomaly.message||"Se detectó una variación inusual.":"No detectamos una anomalía reciente."}</p></div>
  </div>
  <div className="grid lg:grid-cols-2 gap-5">
   <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><Package className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Qué debes reponer</h2><p className="text-xs text-muted-foreground">Prioridad por días estimados hasta agotarse.</p></div></div>{inventory.length===0?<p className="text-sm text-muted-foreground">No hay reposiciones sugeridas con los datos actuales.</p>:<div className="space-y-2">{inventory.slice(0,8).map(p=><div key={p.product_id} className="flex items-center gap-3 border rounded-xl p-3"><div className={`w-2.5 h-2.5 rounded-full ${p.estimated_days_to_stockout!==null&&p.estimated_days_to_stockout<=3?"bg-rose-500":"bg-amber-400"}`}/><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{p.product_name}</p><p className="text-xs text-muted-foreground">Stock {fmtNum(p.stock)} · demanda {fmtNum(p.daily_demand)}/día</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Comprar</p><p className="font-bold">{fmtNum(p.suggested_purchase)}</p></div></div>)}</div>}</section>
   <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><BarChart3 className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Productos que mueven tu negocio</h2><p className="text-xs text-muted-foreground">Clasificación ABC por facturación.</p></div></div>{abc.length===0?<p className="text-sm text-muted-foreground">Aún no hay ventas suficientes.</p>:<div className="space-y-2">{abc.slice(0,8).map(p=><div key={p.product_id} className="flex items-center gap-3 border rounded-xl p-3"><span className={`w-8 h-8 rounded-lg flex items-center justify-center font-extrabold text-sm ${p.abc_class==="A"?"bg-primary/10 text-primary":p.abc_class==="B"?"bg-amber-100 text-amber-700":"bg-secondary text-muted-foreground"}`}>{p.abc_class}</span><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{p.product_name}</p><p className="text-xs text-muted-foreground">{fmtNum(p.units)} uds · margen {fmtNum(p.margin_percent)}%</p></div><div className="text-right"><p className="font-bold">{fmtMoney(p.revenue,currency)}</p><p className="text-xs text-muted-foreground">utilidad {fmtMoney(p.profit,currency)}</p></div></div>)}</div>}</section>
  </div>
  <section className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ShoppingCart className="w-5 h-5 text-primary"/><div><h2 className="font-heading font-bold">Lectura de Cubi</h2><p className="text-xs text-muted-foreground">Recomendaciones explicables, no decisiones automáticas.</p></div></div><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-secondary/60 p-4"><p className="font-semibold text-sm">Inventario</p><p className="text-sm text-muted-foreground mt-1">{inventory.length?`Hay ${inventory.length} productos que merecen revisión de reposición.`:"No detectamos reposiciones prioritarias."}</p></div><div className="rounded-xl bg-secondary/60 p-4"><p className="font-semibold text-sm">Ventas</p><p className="text-sm text-muted-foreground mt-1">{forecast.available?`Cubi estima ${fmtMoney(forecast.predicted_period_revenue,currency)} para los próximos ${forecast.horizon_days} días.`:"Necesitamos más historial para pronosticar."}</p></div><div className="rounded-xl bg-secondary/60 p-4"><p className="font-semibold text-sm">Rentabilidad</p><p className="text-sm text-muted-foreground mt-1">{abc[0]?`${abc[0].product_name} es tu principal producto por facturación acumulada.`:"Registra ventas para comenzar a clasificar tus productos."}</p></div></div></section>
  {data?.history?.observed_days<7&&<div className="text-xs text-muted-foreground flex items-center gap-2"><AlertTriangle className="w-4 h-4"/>Cubi necesita al menos 7 días con ventas para generar un pronóstico confiable.</div>}
 </div>;
}
