import { useCallback,useEffect,useState } from "react";
import { BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend } from "recharts";
import { Download,FileSpreadsheet,HelpCircle,Plus,Trash2,TrendingUp,Wallet,PiggyBank,Percent } from "lucide-react";
import { toast } from "sonner";
import api,{apiError,downloadCsv} from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { fmtDate,fmtMoney,fmtPct,fmtNum,EXPENSE_CATEGORIES } from "../lib/format";
import StatCard from "../components/StatCard";
import InfoHelp from "../components/InfoHelp";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "../components/ui/dialog";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "../components/ui/select";
const CAT_LABELS=Object.fromEntries(EXPENSE_CATEGORIES.map(c=>[c.value,c.label]));
const HELP={
 flujo:["Flujo de ingresos y gastos","Compara los ingresos por ventas con los gastos operativos registrados cada semana. Las compras de mercancía se muestran aparte porque normalmente se convierten en inventario.","Ingresos semanales vs. gastos operativos semanales","Si entran $3.000 y los gastos son $1.200, quedan $1.800 antes de otros movimientos."],
 compras:["Compras de mercancía","Dinero destinado a adquirir productos para vender. Comprar mercancía aumenta inventario y no equivale automáticamente a un gasto operativo.","Suma de compras registradas en los últimos 30 días","Compras $2.000 → aumenta el inventario; el costo afecta la ganancia al vender."],
 categorias:["Gastos por categoría","Distribuye los gastos operativos para identificar dónde se concentra el costo de operar.","Monto de categoría ÷ gastos operativos × 100","Personal $600 de $2.000 → 30%."],
};
function Help({item}){const [title,description,formula,example]=HELP[item];return <InfoHelp title={title}>{description}<span className="block mt-2 rounded-lg bg-secondary/70 p-2"><b>Fórmula:</b> {formula}</span><span className="block mt-1.5"><b>Ejemplo:</b> {example}</span></InfoHelp>}
export default function Finanzas(){
 const{business}=useAuth();const currency=business?.currency||"USD";const[summary,setSummary]=useState(null),[expenses,setExpenses]=useState(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false);const[form,setForm]=useState({category:"otros",description:"",amount:"",date:""});
 const load=useCallback(()=>{api.get("/finances/summary").then(r=>setSummary(r.data)).catch(e=>toast.error(apiError(e)));api.get("/expenses").then(r=>setExpenses(r.data.expenses)).catch(()=>{})},[]);useEffect(()=>{load()},[load]);
 const save=async e=>{e.preventDefault();setSaving(true);try{await api.post("/expenses",{...form,amount:Number(form.amount),date:form.date||null});toast.success("Gasto registrado");setOpen(false);setForm({category:"otros",description:"",amount:"",date:""});load()}catch(err){toast.error(apiError(err))}finally{setSaving(false)}};
 const remove=async exp=>{try{await api.delete(`/expenses/${exp.id}`);toast.success("Gasto eliminado");load()}catch(err){toast.error(apiError(err))}};
 const exportFinance=async()=>{setExporting(true);try{const r=await api.get("/finances/export/xlsx",{responseType:"blob"});const u=URL.createObjectURL(r.data),a=document.createElement("a");a.href=u;a.download="finanzas_cuadraapp.xlsx";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);toast.success("Excel financiero descargado")}catch(e){toast.error(apiError(e,"No pudimos generar el Excel financiero."))}finally{setExporting(false)}};
 return <div className="space-y-5" data-testid="finanzas-page">
  <div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="font-heading text-3xl font-extrabold tracking-tight text-slate-900">Finanzas <Help item="flujo"/></h1><p className="text-sm text-muted-foreground mt-1">Cuánto entra, cuánto sale y cuánto te queda. Sin contabilidad complicada.</p></div><div className="flex gap-2 flex-wrap"><Button variant="outline" data-testid="export-finance-xlsx-btn" onClick={exportFinance} disabled={exporting} className="rounded-xl"><FileSpreadsheet className="w-4 h-4 mr-1.5"/>{exporting?"Generando…":"Exportar Excel"}</Button><Button variant="outline" data-testid="export-expenses-csv-btn" onClick={()=>downloadCsv("/expenses/export/csv","gastos.csv")} className="rounded-xl"><Download className="w-4 h-4 mr-1.5"/>Exportar CSV</Button><Button data-testid="new-expense-btn" onClick={()=>setOpen(true)} className="rounded-xl"><Plus className="w-4 h-4 mr-1.5"/>Registrar gasto</Button></div></div>
  {!summary?<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">{[1,2,3,4].map(i=><div key={i} className="h-32 bg-card border border-border rounded-2xl animate-pulse"/>)}</div>:<>
   <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard testid="fin-ingresos" title="Ingresos (30 días)" value={fmtMoney(summary.ingresos_30,currency)} icon={Wallet} hint="Ventas registradas en los últimos 30 días"/><StatCard testid="fin-gastos" title="Gastos operativos" value={fmtMoney(summary.gastos_operativos_30,currency)} icon={TrendingUp} delay={60} hint="Gastos de funcionamiento; las compras de mercancía se muestran aparte"/><StatCard testid="fin-ganancia" title="Ganancia estimada" value={fmtMoney(summary.ganancia_estimada_30,currency)} icon={PiggyBank} delay={120} hint="Utilidad de las ventas menos gastos operativos"/><StatCard testid="fin-margen" title="Margen" value={fmtPct(summary.margen)} icon={Percent} delay={180} hint={`Margen antes de gastos: ${fmtNum(summary.margen)}%`}/></div>
   <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2 bg-card border border-border rounded-2xl p-5" data-testid="cashflow-card"><div className="flex items-center gap-1"><h3 className="font-heading font-bold text-slate-800 mb-1">Ingresos vs gastos, últimas 8 semanas</h3><Help item="flujo"/></div><p className="text-xs text-muted-foreground mb-4 flex items-center gap-1">Compras de mercancía del período: {fmtMoney(summary.compras_30,currency)} <Help item="compras"/><InfoHelp title="Por qué las compras están aparte"><span>Una compra puede aumentar el inventario. El costo pasa a afectar la utilidad cuando el producto se vende.</span></InfoHelp></p><div className="h-60"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.flujo_semanal} margin={{top:5,right:8,left:-14,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="semana" tick={{fontSize:11}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:11}} tickLine={false} axisLine={false}/><Tooltip formatter={(v,name)=>[fmtMoney(v,currency),name==="ingresos"?"Ingresos":"Gastos"]}/><Legend formatter={v=>v==="ingresos"?"Ingresos":"Gastos"}/><Bar dataKey="ingresos" radius={[6,6,0,0]}/><Bar dataKey="gastos" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="bg-card border border-border rounded-2xl p-5" data-testid="expenses-by-category-card"><div className="flex items-center mb-4"><h3 className="font-heading font-bold text-slate-800">¿En qué se va tu dinero?</h3><Help item="categorias"/></div>{Object.keys(summary.gastos_por_categoria).length===0?<p className="text-sm text-muted-foreground">Sin gastos registrados en los últimos 30 días.</p>:<ul className="space-y-3">{Object.entries(summary.gastos_por_categoria).sort((a,b)=>b[1]-a[1]).map(([cat,amount])=>{const pct=summary.gastos_operativos_30?Math.round(amount/summary.gastos_operativos_30*100):0;return <li key={cat}><div className="flex justify-between text-sm mb-1"><span className="font-medium">{CAT_LABELS[cat]||cat}</span><span className="font-num font-semibold">{fmtMoney(amount,currency)} · {pct}%</span></div><div className="h-2 bg-secondary rounded-full overflow-hidden"><div className="h-full bg-accent rounded-full" style={{width:`${pct}%`}}/></div></li>})}</ul>}</div></div>
  </>}
  <div className="bg-card border border-border rounded-2xl overflow-hidden" data-testid="expenses-table-card"><div className="px-5 py-4 border-b border-border"><div className="flex items-center"><h3 className="font-heading font-bold text-slate-800">Gastos registrados</h3><InfoHelp title="Gastos registrados">Los gastos operativos registrados aquí alimentan la ganancia estimada de Finanzas.</InfoHelp></div></div>{!expenses?<div className="p-6 space-y-3">{[1,2,3,4].map(i=><div key={i} className="h-10 bg-secondary rounded-xl animate-pulse"/>)}</div>:expenses.length===0?<p className="p-10 text-center text-sm text-muted-foreground">Registra tus gastos para conocer mejor el resultado del negocio.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase tracking-wide text-muted-foreground border-b bg-secondary/50"><th className="px-5 py-3">Fecha</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Descripción</th><th className="px-4 py-3 text-right">Monto</th><th className="px-4 py-3"/></tr></thead><tbody className="divide-y">{expenses.map(e=><tr key={e.id} className="hover:bg-secondary/40"><td className="px-5 py-3 text-muted-foreground">{fmtDate(e.created_at)}</td><td className="px-4 py-3"><span className="text-xs bg-secondary px-2 py-0.5 rounded-full">{CAT_LABELS[e.category]||e.category}</span></td><td className="px-4 py-3">{e.description}</td><td className="px-4 py-3 text-right font-num font-semibold text-rose-700">−{fmtMoney(e.amount,currency)}</td><td className="px-4 py-3 text-right"><button data-testid={`expense-delete-${e.id}`} onClick={()=>remove(e)} className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent aria-describedby={undefined} className="max-w-md" data-testid="expense-dialog"><DialogHeader><DialogTitle className="font-heading">Registrar gasto</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div className="space-y-1.5"><Label>Categoría *</Label><Select value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger data-testid="expense-category-select"><SelectValue/></SelectTrigger><SelectContent>{EXPENSE_CATEGORIES.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Descripción *</Label><Input data-testid="expense-description-input" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ej. Alquiler del local"/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-1.5"><Label>Monto *</Label><Input data-testid="expense-amount-input" type="number" min="0.01" step="any" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div className="space-y-1.5"><Label>Fecha</Label><Input data-testid="expense-date-input" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div></div><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?"Guardando…":"Registrar gasto"}</Button></div></form></DialogContent></Dialog>
 </div>
}
