import {useState} from "react";
import {useNavigate} from "react-router-dom";
import {ArrowLeft,ArrowRight,PackagePlus,Store,Trash2,Lightbulb} from "lucide-react";
import {toast} from "sonner";
import api,{apiError} from "../lib/api";
import {useAuth} from "../context/AuthContext";
import {BUSINESS_TYPES,CURRENCIES,fmtBs} from "../lib/format";
import {Button} from "../components/ui/button";
import {Input} from "../components/ui/input";
import {Label} from "../components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "../components/ui/select";

const STEPS=["Tu negocio","Rubro","Moneda","Productos","Listo"];
const TARGET_MARGIN=35;
const suggestPrice=(cost)=>{const n=Number(cost)||0;return n>0?Number((n/(1-TARGET_MARGIN/100)).toFixed(2)):0;};

export default function Onboarding(){
 const{refreshUser}=useAuth();const navigate=useNavigate();
 const[step,setStep]=useState(0);const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({name:"",type:"",currency:"USD"});const[products,setProducts]=useState([]);
 const[draft,setDraft]=useState({name:"",category:"",purchase_price:"",sale_price:"",stock:""});
 const symbol=form.currency==="VES"?"Bs":"$";
 const suggested=suggestPrice(draft.purchase_price);
 const addProduct=()=>{if(!draft.name.trim())return;const purchase=Number(draft.purchase_price)||0;const sale=draft.sale_price===""?suggestPrice(purchase):Number(draft.sale_price)||0;setProducts([...products,{name:draft.name.trim(),category:draft.category||"General",purchase_price:purchase,sale_price:sale,stock:Number(draft.stock)||0}]);setDraft({name:"",category:"",purchase_price:"",sale_price:"",stock:""});};
 const finish=async()=>{setSaving(true);try{await api.post("/business",{...form,initial_products:products});await refreshUser();toast.success("¡Tu negocio está listo!");navigate("/dashboard",{replace:true});}catch(e){toast.error(apiError(e,"No pudimos guardar tu negocio."));}finally{setSaving(false);}};
 const canNext=step===0?form.name.trim().length>=2:step===1?!!form.type:true;
 return <div className="min-h-screen bg-background flex items-center justify-center p-4"><div className="w-full max-w-lg">
  <div className="flex items-center gap-2.5 mb-8 justify-center"><div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center"><Store className="w-5 h-5 text-white"/></div><span className="font-heading font-extrabold text-xl">CuadrApp</span></div>
  <div className="flex items-center justify-center gap-2 mb-6">{STEPS.map((s,i)=><div key={s} className="flex items-center gap-2"><div title={s} className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${i<=step?"bg-primary text-white":"bg-secondary text-muted-foreground"}`}>{i+1}</div>{i<4&&<div className={`w-6 h-0.5 ${i<step?"bg-primary":"bg-border"}`}/>}</div>)}</div>
  <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 shadow-sm">
   {step===0&&<div className="space-y-4"><h1 className="font-heading text-2xl sm:text-3xl font-extrabold">¿Cómo se llama tu negocio?</h1><p className="text-sm text-muted-foreground">Ej. Ferretería El Candado, Bodega Don José, Salón Bella.</p><div className="space-y-1.5"><Label>Nombre del negocio</Label><Input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Mi negocio" className="h-12 text-base"/></div></div>}
   {step===1&&<div className="space-y-4"><h1 className="font-heading text-2xl sm:text-3xl font-extrabold">¿Qué tipo de negocio tienes?</h1><p className="text-sm text-muted-foreground">Esto nos ayuda a adaptar recomendaciones e indicadores.</p><Select value={form.type} onValueChange={v=>setForm({...form,type:v})}><SelectTrigger className="h-12"><SelectValue placeholder="Elige tu rubro"/></SelectTrigger><SelectContent>{BUSINESS_TYPES.map(t=><SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}</SelectContent></Select></div>}
   {step===2&&<div className="space-y-4"><h1 className="font-heading text-2xl sm:text-3xl font-extrabold">¿En qué moneda trabajas?</h1><p className="text-sm text-muted-foreground">Puedes trabajar en bolívares y luego consultar equivalencias usando la tasa configurada.</p><Select value={form.currency} onValueChange={v=>setForm({...form,currency:v})}><SelectTrigger className="h-12"><SelectValue/></SelectTrigger><SelectContent>{CURRENCIES.map(c=><SelectItem key={c.code} value={c.code}>{c.label}</SelectItem>)}</SelectContent></Select><div className="bg-primary/5 rounded-xl p-3 text-sm">Tus precios se guardarán en <strong>{form.currency==="VES"?"Bs":"USD"}</strong>. Más adelante podrás configurar la tasa de referencia.</div></div>}
   {step===3&&<div className="space-y-4"><div><h1 className="font-heading text-2xl sm:text-3xl font-extrabold">Agrega tus primeros productos</h1><p className="text-sm text-muted-foreground mt-1">Primero registra tu costo de compra. CuadrApp puede sugerirte un precio de venta.</p></div>
    {products.length>0&&<div className="space-y-2 max-h-40 overflow-y-auto">{products.map((p,i)=><div key={i} className="flex items-center gap-3 bg-secondary rounded-xl px-3.5 py-2.5 text-sm"><PackagePlus className="w-4 h-4 text-primary"/><span className="flex-1 min-w-0"><span className="font-medium truncate block">{p.name}</span><span className="text-[11px] text-muted-foreground">{p.category}</span></span><span className="font-num text-xs text-muted-foreground whitespace-nowrap">Compra {symbol}{fmtNumSafe(p.purchase_price)} · Venta {symbol}{fmtNumSafe(p.sale_price)}</span><button type="button" onClick={()=>setProducts(products.filter((_,j)=>j!==i))}><Trash2 className="w-4 h-4"/></button></div>)}</div>}
    <div className="grid grid-cols-2 gap-3"><div className="col-span-2 space-y-1.5"><Label>Nombre del producto</Label><Input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ej. Harina de maíz"/></div><div className="space-y-1.5"><Label>Categoría</Label><Input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} placeholder="General"/></div><div className="space-y-1.5"><Label>Stock inicial</Label><Input type="number" min="0" step="any" value={draft.stock} onChange={e=>setDraft({...draft,stock:e.target.value})} placeholder="0"/></div><div className="space-y-1.5"><Label>Precio de compra</Label><Input type="number" min="0" step="any" value={draft.purchase_price} onChange={e=>setDraft({...draft,purchase_price:e.target.value})} placeholder="Costo"/></div><div className="space-y-1.5"><Label>Precio de venta</Label><Input type="number" min="0" step="any" value={draft.sale_price} onChange={e=>setDraft({...draft,sale_price:e.target.value})} placeholder={suggested?String(suggested):"Se sugiere automáticamente"}/></div></div>
    {suggested>0&&<div className="flex gap-2 bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-900"><Lightbulb className="w-4 h-4 shrink-0 mt-0.5"/><span><strong>Sugerencia:</strong> {symbol}{fmtNumSafe(suggested)} usando un margen objetivo de {TARGET_MARGIN}%. No es un precio de mercado; puedes modificarlo.</span></div>}
    <Button type="button" variant="outline" onClick={addProduct} disabled={!draft.name.trim()} className="w-full">Agregar producto</Button>
   </div>}
   {step===4&&<div className="space-y-4 text-center py-4"><div className="w-16 h-16 rounded-full bg-emerald-100 flex items-center justify-center mx-auto"><Store className="w-8 h-8 text-primary"/></div><h1 className="font-heading text-2xl sm:text-3xl font-extrabold">¡Todo listo, {form.name}!</h1><p className="text-sm text-muted-foreground">Tu panel está preparado. Registra compras y ventas para que CuadrApp pueda analizar tu negocio.</p><div className="grid grid-cols-2 gap-3 text-left"><div className="bg-secondary rounded-xl p-3"><p className="text-xs text-muted-foreground">Productos iniciales</p><p className="font-heading font-bold text-xl">{products.length}</p></div><div className="bg-secondary rounded-xl p-3"><p className="text-xs text-muted-foreground">Moneda</p><p className="font-heading font-bold text-xl">{form.currency==="VES"?"Bs":"USD"}</p></div></div></div>}
   <div className="flex items-center justify-between mt-8"><Button variant="ghost" onClick={()=>setStep(step-1)} disabled={step===0||saving}><ArrowLeft className="w-4 h-4 mr-1.5"/>Atrás</Button>{step<4?<div className="flex gap-2">{step===3&&<Button variant="ghost" onClick={()=>setStep(4)}>Omitir</Button>}<Button onClick={()=>setStep(step+1)} disabled={!canNext} className="rounded-xl">Continuar<ArrowRight className="w-4 h-4 ml-1.5"/></Button></div>:<Button onClick={finish} disabled={saving} className="rounded-xl">{saving?"Guardando…":"Ir a mi Dashboard"}<ArrowRight className="w-4 h-4 ml-1.5"/></Button>}</div>
  </div></div></div>;
}
const fmtNumSafe=n=>Number(n||0).toLocaleString("es-VE",{minimumFractionDigits:2,maximumFractionDigits:2});
