import { useCallback,useEffect,useState } from "react";
import { Plus,ShieldCheck,Store,TrendingUp,Users,CreditCard,Clock3,RefreshCw,Receipt } from "lucide-react";
import { toast } from "sonner";
import api,{apiError} from "../lib/api";
import { fmtDate,fmtMoney,fmtNum } from "../lib/format";
import StatCard from "../components/StatCard";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "../components/ui/dialog";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "../components/ui/select";
import { Switch } from "../components/ui/switch";
const CATS=[{value:"infraestructura",label:"Infraestructura"},{value:"marketing",label:"Marketing"},{value:"soporte",label:"Soporte"},{value:"licencias",label:"Licencias"},{value:"otros",label:"Otros"}];
const EMPTY_PLAN={name:"",description:"",monthly_price_usd:"",active:true,features:[]};
export default function Plataforma(){
 const[data,setData]=useState(null),[expenses,setExpenses]=useState([]),[plans,setPlans]=useState([]),[subs,setSubs]=useState([]),[pending,setPending]=useState([]),[billing,setBilling]=useState([]),[metrics,setMetrics]=useState(null);const[tab,setTab]=useState("resumen"),[open,setOpen]=useState(false),[billOpen,setBillOpen]=useState(false),[planOpen,setPlanOpen]=useState(false),[saving,setSaving]=useState(false),[editingPlan,setEditingPlan]=useState(null),[selectedSub,setSelectedSub]=useState(null);
 const[form,setForm]=useState({category:"infraestructura",description:"",amount:"",date:""}),[billForm,setBillForm]=useState({amount:"",payment_method:"transferencia",paid_at:"",notes:""}),[planForm,setPlanForm]=useState(EMPTY_PLAN);
 const load=useCallback(async()=>{try{const[o,e,p,s,u,b,m]=await Promise.all([api.get("/platform/overview"),api.get("/platform/expenses"),api.get("/platform/plans"),api.get("/platform/subscriptions"),api.get("/platform/pending-users"),api.get("/platform/billing"),api.get("/platform/billing-metrics")]);setData(o.data);setExpenses(e.data.expenses||[]);setPlans(p.data.plans||[]);setSubs(s.data.subscriptions||[]);setPending(u.data.users||[]);setBilling(b.data.billing||[]);setMetrics(m.data)}catch(e){toast.error(apiError(e))}},[]);useEffect(()=>{load()},[load]);
 const toggle=async(b,active)=>{try{await api.put(`/platform/businesses/${b.id}/status`,{active});toast.success(active?"Negocio habilitado":"Negocio deshabilitado");load()}catch(e){toast.error(apiError(e))}};const addExpense=async e=>{e.preventDefault();setSaving(true);try{await api.post("/platform/expenses",{...form,amount:Number(form.amount),date:form.date||null});toast.success("Gasto registrado");setOpen(false);load()}catch(x){toast.error(apiError(x))}finally{setSaving(false)}};const savePlan=async e=>{e.preventDefault();setSaving(true);try{const body={...planForm,monthly_price_usd:Number(planForm.monthly_price_usd)};if(editingPlan)await api.put(`/platform/plans/${editingPlan.id}`,body);else await api.post("/platform/plans",body);toast.success("Plan guardado");setPlanOpen(false);load()}catch(x){toast.error(apiError(x))}finally{setSaving(false)}};const deletePlan=async p=>{if(!confirm(`¿Eliminar ${p.name}?`))return;try{await api.delete(`/platform/plans/${p.id}`);load()}catch(e){toast.error(apiError(e))}};const approve=async u=>{try{await api.put(`/platform/users/${u.id}/approval`,{approved:true});load()}catch(e){toast.error(apiError(e))}};const changeSub=async(s,status)=>{try{await api.patch(`/platform/subscriptions/${s.id}/status?status=${status}`);load()}catch(e){toast.error(apiError(e))}};const registerBilling=async e=>{e.preventDefault();if(!selectedSub)return;setSaving(true);try{await api.post("/platform/billing",{subscription_id:selectedSub.id,amount:Number(billForm.amount),payment_method:billForm.payment_method,paid_at:billForm.paid_at?new Date(billForm.paid_at).toISOString():null,notes:billForm.notes});toast.success("Cobro registrado");setBillOpen(false);load()}catch(x){toast.error(apiError(x))}finally{setSaving(false)}};
 if(!data)return <div className="p-8 text-sm text-muted-foreground">Cargando plataforma…</div>;const s=data.stats;const tabs=[['resumen','Resumen'],['clientes','Clientes'],['planes','Planes y precios'],['cobros','Cobros'],['gastos','Costos']];return <div className="space-y-5" data-testid="plataforma-page"><div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="font-heading text-3xl font-extrabold flex items-center gap-2"><ShieldCheck className="w-7 h-7 text-primary"/>Plataforma</h1><p className="text-sm text-muted-foreground">Gobernanza, clientes, planes, cobros y costos de CuadraApp.</p></div><Button variant="outline" onClick={load}><RefreshCw className="w-4 h-4 mr-2"/>Actualizar</Button></div><div className="flex gap-1 p-1 bg-secondary rounded-xl overflow-x-auto">{tabs.map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`px-4 py-2 rounded-lg text-sm whitespace-nowrap ${tab===v?'bg-background shadow-sm':''}`}>{l}</button>)}</div>
 {tab==='resumen'&&<><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4"><StatCard title="Clientes" value={fmtNum(s.total)} icon={Store}/><StatCard title="Activos" value={fmtNum(s.activos)} icon={Users}/><StatCard title="MRR" value={fmtMoney(s.mrr_usd||0,'USD')} icon={CreditCard}/><StatCard title="Cobrado este mes" value={fmtMoney(s.cobrado_mes_usd||0,'USD')} icon={Receipt}/><StatCard title="Neto del mes" value={fmtMoney(s.neto_mes_usd||0,'USD')} icon={TrendingUp}/></div><div className="grid md:grid-cols-3 gap-4"><div className="bg-card border rounded-2xl p-5"><p className="text-sm text-muted-foreground">Costos del mes</p><p className="text-3xl font-bold mt-2">{fmtMoney(metrics?.platform_costs_usd||0,'USD')}</p></div><div className="bg-card border rounded-2xl p-5"><p className="text-sm text-muted-foreground">Suscripciones activas</p><p className="text-3xl font-bold mt-2">{fmtNum(s.suscripciones_activas||0)}</p></div><div className="bg-card border rounded-2xl p-5"><p className="text-sm text-muted-foreground">Pendientes / vencidas</p><p className="text-3xl font-bold mt-2">{fmtNum(metrics?.due_soon?.length||0)}</p></div></div></>}
 {tab==='clientes'&&<div className="space-y-4"><div className="bg-card border rounded-2xl overflow-hidden"><div className="px-5 py-4 border-b"><h3 className="font-heading font-bold">Negocios registrados</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-muted-foreground bg-secondary/50"><th className="px-5 py-3">Negocio</th><th>Dueño</th><th>Plan</th><th>Vencimiento</th><th>Activo</th></tr></thead><tbody className="divide-y">{data.businesses.map(b=><tr key={b.id}><td className="px-5 py-3"><b>{b.name}</b><div className="text-xs text-muted-foreground">{b.owner_email}</div></td><td>{b.owner_name}</td><td>{b.plan_name||'Sin plan'}</td><td>{b.subscription_due_date?fmtDate(b.subscription_due_date):'—'}</td><td><Switch checked={b.active} onCheckedChange={v=>toggle(b,v)}/></td></tr>)}</tbody></table></div></div><div className="bg-card border rounded-2xl p-5"><h3 className="font-heading font-bold mb-3">Solicitudes pendientes ({pending.length})</h3>{pending.map(u=><div key={u.id} className="flex items-center gap-3 py-3 border-b"><div className="flex-1"><b>{u.name||u.email}</b><div className="text-xs text-muted-foreground">{u.email}</div></div><Button size="sm" onClick={()=>approve(u)}>Aprobar</Button></div>)}</div></div>}
 {tab==='planes'&&<div className="space-y-4"><div className="flex justify-end"><Button onClick={()=>{setEditingPlan(null);setPlanForm(EMPTY_PLAN);setPlanOpen(true)}}><Plus className="w-4 h-4 mr-2"/>Nuevo plan</Button></div><div className="grid md:grid-cols-2 gap-4">{plans.map(p=><div key={p.id} className="bg-card border rounded-2xl p-5"><h3 className="text-xl font-bold">{p.name}</h3><p className="text-sm text-muted-foreground">{p.description}</p><p className="text-3xl font-bold mt-5">{fmtMoney(p.monthly_price_usd,'USD')}<span className="text-sm font-normal"> / mes</span></p><div className="flex gap-2 mt-5"><Button variant="outline" onClick={()=>{setEditingPlan(p);setPlanForm({name:p.name,description:p.description||'',monthly_price_usd:p.monthly_price_usd,active:p.active,features:p.features||[]});setPlanOpen(true)}}>Editar</Button><Button variant="ghost" onClick={()=>deletePlan(p)} className="text-rose-600">Eliminar</Button></div></div>)}</div></div>}
 {tab==='cobros'&&<div className="space-y-4"><div className="bg-card border rounded-2xl overflow-hidden"><div className="px-5 py-4 border-b"><h3 className="font-heading font-bold">Suscripciones y cobros</h3></div><div className="divide-y">{subs.map(x=><div key={x.id} className="px-5 py-4 flex items-center gap-3 flex-wrap"><div className="flex-1 min-w-[220px]"><b>{x.plan_name}</b><div className="text-xs text-muted-foreground">{x.business_id}</div></div><span className="font-semibold">{fmtMoney(x.monthly_price_usd,'USD')}/mes</span><span className="text-sm flex items-center gap-1"><Clock3 className="w-4 h-4"/>{x.due_date||'Sin fecha'}</span><Select value={x.status} onValueChange={v=>changeSub(x,v)}><SelectTrigger className="w-32"><SelectValue/></SelectTrigger><SelectContent>{['activo','pendiente','vencido','cancelado'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Button size="sm" onClick={()=>{setSelectedSub(x);setBillForm({amount:x.monthly_price_usd,payment_method:'transferencia',paid_at:'',notes:''});setBillOpen(true)}}><Receipt className="w-4 h-4 mr-1"/>Cobrar</Button></div>)}</div></div><div className="bg-card border rounded-2xl overflow-hidden"><div className="px-5 py-4 border-b"><h3 className="font-heading font-bold">Historial</h3></div>{billing.map(x=><div key={x.id} className="px-5 py-3 border-b flex gap-3"><span className="flex-1">{x.business_id}</span><span>{x.payment_method}</span><b>{fmtMoney(x.amount,'USD')}</b><span className="text-xs text-muted-foreground">{fmtDate(x.paid_at)}</span></div>)}{!billing.length&&<p className="p-8 text-center text-sm text-muted-foreground">Sin cobros registrados.</p>}</div></div>}
 {tab==='gastos'&&<><div className="flex justify-end"><Button onClick={()=>setOpen(true)}><Plus className="w-4 h-4 mr-2"/>Gasto de plataforma</Button></div><div className="bg-card border rounded-2xl overflow-hidden">{expenses.map(x=><div key={x.id} className="px-5 py-3 flex gap-3 border-b"><span className="flex-1">{x.description}</span><span>{x.category}</span><b className="text-rose-700">−{fmtMoney(x.amount,'USD')}</b></div>)}</div></>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Gasto de plataforma</DialogTitle></DialogHeader><form onSubmit={addExpense} className="space-y-4"><Label>Categoría</Label><Select value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{CATS.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select><Label>Descripción</Label><Input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Label>Monto USD</Label><Input type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Button disabled={saving}>{saving?'Guardando…':'Registrar'}</Button></form></DialogContent></Dialog><Dialog open={billOpen} onOpenChange={setBillOpen}><DialogContent><DialogHeader><DialogTitle>Registrar cobro</DialogTitle></DialogHeader><form onSubmit={registerBilling} className="space-y-4"><p className="text-sm text-muted-foreground">{selectedSub?.plan_name}</p><Label>Monto USD</Label><Input type="number" min="0.01" step="0.01" required value={billForm.amount} onChange={e=>setBillForm({...billForm,amount:e.target.value})}/><Label>Método de pago</Label><Input required value={billForm.payment_method} onChange={e=>setBillForm({...billForm,payment_method:e.target.value})}/><Label>Notas</Label><Input value={billForm.notes} onChange={e=>setBillForm({...billForm,notes:e.target.value})}/><Button disabled={saving}>{saving?'Registrando…':'Confirmar cobro'}</Button></form></DialogContent></Dialog><Dialog open={planOpen} onOpenChange={setPlanOpen}><DialogContent><DialogHeader><DialogTitle>{editingPlan?'Editar plan':'Nuevo plan'}</DialogTitle></DialogHeader><form onSubmit={savePlan} className="space-y-4"><Label>Nombre</Label><Input required value={planForm.name} onChange={e=>setPlanForm({...planForm,name:e.target.value})}/><Label>Descripción</Label><Input value={planForm.description} onChange={e=>setPlanForm({...planForm,description:e.target.value})}/><Label>Precio mensual USD</Label><Input type="number" min="0.01" step="0.01" required value={planForm.monthly_price_usd} onChange={e=>setPlanForm({...planForm,monthly_price_usd:e.target.value})}/><div className="flex items-center gap-2"><Switch checked={planForm.active} onCheckedChange={v=>setPlanForm({...planForm,active:v})}/><Label>Activo</Label></div><Button disabled={saving}>{saving?'Guardando…':'Guardar plan'}</Button></form></DialogContent></Dialog></div>;
}