import { useCallback,useEffect,useState } from "react";
import { Lightbulb,Percent,Tag,RefreshCw } from "lucide-react";
import { toast } from "sonner";
import api,{apiError} from "../lib/api";
import { Button } from "../components/ui/button";
import { fmtMoney,fmtNum } from "../lib/format";
export default function Promociones(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(null);
 const load=useCallback(async()=>{setLoading(true);try{const{data}=await api.get("/promotions/recommendations");setItems(data.recommendations||[])}catch(e){toast.error(apiError(e))}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const create=async item=>{setSaving(item.product_id);try{await api.post("/promotions",{product_id:item.product_id,discount_percent:item.suggested_discount_percent});toast.success(`Promoción creada para ${item.product_name}`);load()}catch(e){toast.error(apiError(e))}finally{setSaving(null)}};
 return <div className="space-y-5" data-testid="promociones-page"><div className="flex items-center justify-between gap-3"><div><h1 className="font-heading text-3xl font-extrabold flex items-center gap-2"><Tag className="w-7 h-7 text-primary"/>Promociones</h1><p className="text-sm text-muted-foreground mt-1">Recomendaciones basadas en rotación, stock, costo y margen. El sistema recomienda; tú decides.</p></div><Button variant="outline" onClick={load} disabled={loading} className="rounded-xl"><RefreshCw className={`w-4 h-4 mr-1.5 ${loading?"animate-spin":""}`}/>Actualizar análisis</Button></div><div className="rounded-2xl border bg-primary/5 p-4 flex gap-3"><Lightbulb className="w-5 h-5 text-primary shrink-0 mt-0.5"/><div><p className="font-semibold text-sm">Asesoría, no órdenes</p><p className="text-xs text-muted-foreground mt-1">Las sugerencias consideran datos internos de CuadrApp. No sustituyen tu criterio ni representan un precio obligatorio de mercado.</p></div></div>{loading?<div className="grid md:grid-cols-2 gap-4">{[1,2,3,4].map(i=><div key={i} className="h-44 rounded-2xl bg-secondary animate-pulse"/>)}</div>:items.length===0?<div className="bg-card border rounded-2xl p-12 text-center"><Percent className="w-10 h-10 mx-auto text-muted-foreground"/><p className="font-bold mt-3">No hay promociones sugeridas</p><p className="text-sm text-muted-foreground mt-1">Cuando CuadrApp detecte stock elevado frente a la rotación, aparecerán aquí.</p></div>:<div className="grid md:grid-cols-2 gap-4">{items.map(item=><article key={item.product_id} className="bg-card border rounded-2xl p-5"><div className="flex justify-between gap-3"><div><p className="font-bold">{item.product_name}</p><p className="text-xs text-muted-foreground mt-1">{item.reason}</p></div><span className="text-xs font-bold rounded-full bg-primary/10 text-primary px-2.5 py-1 h-fit">{fmtNum(item.suggested_discount_percent)}% sugerido</span></div><div className="grid grid-cols-3 gap-3 mt-5 text-sm"><div><p className="text-xs text-muted-foreground">Stock</p><b>{fmtNum(item.stock)}</b></div><div><p className="text-xs text-muted-foreground">Precio actual</p><b>{fmtMoney(item.sale_price)}</b></div><div><p className="text-xs text-muted-foreground">Escenario promo</p><b>{fmtMoney(item.suggested_price)}</b></div></div><div className="mt-4 p-3 rounded-xl bg-secondary/60 text-xs"><span className="text-muted-foreground">Margen estimado después:</span> <b>{fmtNum(item.estimated_margin_after)}%</b> · Confianza: <b>{item.confidence}</b></div><Button className="w-full mt-4 rounded-xl" onClick={()=>create(item)} disabled={saving===item.product_id}>{saving===item.product_id?"Creando…":"Crear esta promoción"}</Button></article>)}</div>}</div>;
}
