import { useCallback,useEffect,useMemo,useState } from "react";
import { LineChart,SlidersHorizontal,Target,TrendingDown,TrendingUp,Package,RefreshCw } from "lucide-react";
import { toast } from "sonner";
import api,{apiError} from "../lib/api";
import { fmtMoney,fmtNum } from "../lib/format";
import { Input } from "../components/ui/input";

export default function Proyeccion(){
 const[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[days,setDays]=useState(30),[salesFactor,setSalesFactor]=useState(100),[extraExpenses,setExtraExpenses]=useState(0);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/products");setProducts(r.data.products||[])}catch(e){toast.error(apiError(e))}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const data=useMemo(()=>{const stockValue=products.reduce((s,p)=>s+(Number(p.stock)||0)*(Number(p.purchase_price)||0),0);const currentInventory=products.reduce((s,p)=>s+(Number(p.stock)||0)*(Number(p.sale_price)||0),0);const estimatedDailyRevenue=products.reduce((s,p)=>{const stock=Number(p.stock)||0;const min=Math.max(Number(p.min_stock)||0,1);const velocity=stock>min?Math.min(stock-min,Math.max(min*.35,1)):Math.max(stock*.2,.1);return s+(velocity*(Number(p.sale_price)||0))},0)/Math.max(Number(days),1);const monthlyRevenue=estimatedDailyRevenue*Number(days)*salesFactor/100;const marginRate=products.length?products.reduce((s,p)=>{const sell=Number(p.sale_price)||0,cost=Number(p.purchase_price)||0;return s+(sell?Math.max(0,(sell-cost)/sell):0)},0)/products.length:.25;const gross=monthlyRevenue*marginRate;const operating=Number(extraExpenses)||0;const breakEvenRevenue=operating/(marginRate||.01);const result=gross-operating;const unitsToBreakEven=products.length?Math.ceil((breakEvenRevenue/Math.max(monthlyRevenue,1))*products.reduce((s,p)=>s+Math.max(Number(p.stock)||0,0),0)):0;return{stockValue,currentInventory,estimatedDailyRevenue,monthlyRevenue,marginRate,gross,operating,breakEvenRevenue,result,unitsToBreakEven}},[products,days,salesFactor,extraExpenses]);
 const positive=data.result>=0;
 return <div className="space-y-5" data-testid="proyeccion-page"><div className="flex items-center justify-between gap-3"><div><h1 className="font-heading text-3xl font-extrabold flex items-center gap-2"><LineChart className="w-7 h-7 text-primary"/>Proyección</h1><p className="text-sm text-muted-foreground mt-1">Simula escenarios antes de tomar decisiones. Los resultados son orientativos, no una garantía.</p></div><button onClick={load} className="h-10 px-3 rounded-xl border flex items-center gap-2 text-sm font-semibold"><RefreshCw className="w-4 h-4"/>Actualizar datos</button></div>
 <div className="grid lg:grid-cols-[1fr_1.4fr] gap-5"><section className="bg-card border rounded-2xl p-5 space-y-5"><div className="flex items-center gap-2"><SlidersHorizontal className="w-5 h-5 text-primary"/><h2 className="font-heading font-bold">Simulador</h2></div><div><label className="text-sm font-semibold">Días proyectados</label><Input type="number" min="7" max="90" value={days} onChange={e=>setDays(e.target.value)} className="mt-1.5"/></div><div><div className="flex justify-between text-sm"><label className="font-semibold">Nivel de ventas esperado</label><b>{salesFactor}%</b></div><input type="range" min="25" max="200" step="5" value={salesFactor} onChange={e=>setSalesFactor(e.target.value)} className="w-full mt-3"/><div className="flex justify-between text-xs text-muted-foreground"><span>25% · muy bajo</span><span>100% · base</span><span>200% · alto</span></div></div><div><label className="text-sm font-semibold">Gastos operativos adicionales</label><Input type="number" min="0" step="0.01" value={extraExpenses} onChange={e=>setExtraExpenses(e.target.value)} placeholder="0" className="mt-1.5"/></div><div className="rounded-xl bg-secondary/60 p-4 text-xs text-muted-foreground"><b className="text-foreground">Cómo funciona:</b> CuadrApp usa el stock, costos, precios y una estimación de rotación para construir un escenario. Cambia las variables y observa cómo se mueve el resultado.</div></section>
 <section className="space-y-4"><div className={`rounded-2xl border p-5 ${positive?"bg-emerald-50/70":"bg-rose-50/70"}`}><div className="flex items-start gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${positive?"bg-emerald-100 text-emerald-700":"bg-rose-100 text-rose-700"}`}>{positive?<TrendingUp className="w-5 h-5"/>:<TrendingDown className="w-5 h-5"/>}</div><div><p className="text-xs uppercase tracking-wide font-bold text-muted-foreground">Resultado estimado</p><p className={`text-3xl font-heading font-extrabold mt-1 ${positive?"text-emerald-700":"text-rose-700"}`}>{fmtMoney(data.result)}</p><p className="text-sm mt-1">{positive?"El escenario termina por encima del punto de equilibrio.":"Con este escenario terminarías por debajo del punto de equilibrio."}</p></div></div></div><div className="grid sm:grid-cols-2 gap-3">{[["Ventas proyectadas",fmtMoney(data.monthlyRevenue)],["Margen bruto estimado",`${fmtNum(data.marginRate*100)}%`],["Punto de equilibrio",fmtMoney(data.breakEvenRevenue)],["Ganancia bruta",fmtMoney(data.gross)],["Valor de venta del stock",fmtMoney(data.currentInventory)],["Costo del stock",fmtMoney(data.stockValue)]].map(([l,v])=><div key={l} className="bg-card border rounded-2xl p-4"><p className="text-xs text-muted-foreground">{l}</p><p className="font-heading text-xl font-extrabold mt-1">{v}</p></div>)}</div><div className="bg-card border rounded-2xl p-5"><div className="flex items-center gap-2"><Target className="w-5 h-5 text-primary"/><div><h3 className="font-heading font-bold">Guía de acción</h3><p className="text-xs text-muted-foreground">Qué tendría que ocurrir para acercarte al equilibrio.</p></div></div><div className="mt-4 grid sm:grid-cols-3 gap-3 text-sm"><div className="rounded-xl bg-secondary/60 p-3"><Package className="w-4 h-4 mb-2 text-primary"/><p className="text-xs text-muted-foreground">Stock disponible</p><b>{fmtNum(products.reduce((s,p)=>s+(Number(p.stock)||0),0))} unidades</b></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Venta diaria estimada</p><b>{fmtMoney(data.estimatedDailyRevenue)}</b></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Cobertura al equilibrio</p><b>{data.result>=0?"Escenario cubierto":`${fmtNum(data.unitsToBreakEven)} unidades aprox.`}</b></div></div></div></section></div>{loading&&<div className="text-xs text-muted-foreground">Actualizando datos…</div>}</div>;
}
