import {useEffect,useMemo,useState} from "react";
import {ChefHat,Plus,Trash2} from "lucide-react";
import {toast} from "sonner";
import api,{apiError} from "../lib/api";
import {useAuth} from "../context/AuthContext";
import {fmtMoney,fmtNum} from "../lib/format";
import {Button} from "../components/ui/button";
import {Input} from "../components/ui/input";
import {Label} from "../components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "../components/ui/select";

export default function Recetas(){
 const{business}=useAuth();const currency=business?.currency||"USD";const[recipes,setRecipes]=useState([]);const[products,setProducts]=useState([]);const[open,setOpen]=useState(false);const[name,setName]=useState("");const[output,setOutput]=useState("");const[yieldQty,setYieldQty]=useState("1");const[ingredients,setIngredients]=useState([{product_id:"",quantity:"1"}]);const[saving,setSaving]=useState(false);
 const load=()=>api.get("/recipes").then(r=>setRecipes(r.data.recipes)).catch(e=>toast.error(apiError(e)));useEffect(()=>{load();api.get("/products").then(r=>setProducts(r.data.products)).catch(()=>{});},[]);
 const cost=useMemo(()=>ingredients.reduce((s,i)=>{const p=products.find(x=>x.id===i.product_id);return s+(Number(i.quantity)||0)*Number(p?.purchase_price||0);},0),[ingredients,products]);
 const save=async e=>{e.preventDefault();setSaving(true);try{await api.post("/recipes",{name,output_product_id:output||null,yield_quantity:Number(yieldQty),ingredients:ingredients.filter(i=>i.product_id).map(i=>({product_id:i.product_id,quantity:Number(i.quantity)}))});toast.success("Receta guardada");setOpen(false);setName("");setOutput("");setYieldQty("1");setIngredients([{product_id:"",quantity:"1"}]);load();}catch(err){toast.error(apiError(err));}finally{setSaving(false);}};
 return <div className="space-y-5"><div className="flex justify-between items-center gap-3 flex-wrap"><div><h1 className="font-heading text-3xl font-extrabold">Recetas y materias primas</h1><p className="text-sm text-muted-foreground mt-1">Relaciona productos, calcula costos y prepara productos terminados.</p></div><Button onClick={()=>setOpen(true)} className="rounded-xl"><Plus className="w-4 h-4 mr-1.5"/>Nueva receta</Button></div>
 <div className="grid md:grid-cols-2 gap-4">{recipes.length===0?<div className="md:col-span-2 bg-card border border-border rounded-2xl p-10 text-center"><ChefHat className="w-10 h-10 mx-auto text-muted-foreground mb-3"/><p className="font-semibold">Aún no tienes recetas</p><p className="text-sm text-muted-foreground mt-1">Crea una para controlar materias primas y costo por unidad.</p></div>:recipes.map(r=><div key={r.id} className="bg-card border border-border rounded-2xl p-5"><div className="flex justify-between gap-3"><div><h3 className="font-heading font-bold">{r.name}</h3><p className="text-xs text-muted-foreground">Rendimiento: {fmtNum(r.yield_quantity)} · {r.ingredients.length} ingredientes</p></div><ChefHat className="w-5 h-5 text-primary"/></div><div className="mt-4 space-y-1 text-sm">{r.ingredients.map((i,n)=><div key={n} className="flex justify-between"><span>{i.name}</span><span className="font-num text-muted-foreground">{fmtNum(i.quantity)} {i.unit}</span></div>)}</div><div className="mt-4 pt-3 border-t border-border flex justify-between font-semibold"><span>Costo estimado</span><span className="font-num">{fmtMoney(r.cost_per_output,currency)} / unidad</span></div></div>)}</div>
 {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="bg-card border border-border rounded-2xl p-6 w-full max-w-xl max-h-[90vh] overflow-y-auto"><h2 className="font-heading text-xl font-bold mb-4">Nueva receta</h2><form onSubmit={save} className="space-y-4"><div><Label>Nombre</Label><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Arepa rellena"/></div><div className="grid grid-cols-2 gap-3"><div><Label>Producto terminado</Label><Select value={output} onValueChange={setOutput}><SelectTrigger><SelectValue placeholder="Opcional"/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Rendimiento</Label><Input type="number" min="0.01" step="any" value={yieldQty} onChange={e=>setYieldQty(e.target.value)}/></div></div><div className="space-y-2"><Label>Materias primas</Label>{ingredients.map((i,n)=><div key={n} className="grid grid-cols-12 gap-2"><div className="col-span-8"><Select value={i.product_id} onValueChange={v=>setIngredients(ingredients.map((x,j)=>j===n?{...x,product_id:v}:x))}><SelectTrigger><SelectValue placeholder="Selecciona producto"/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><Input className="col-span-3" type="number" min="0.01" step="any" value={i.quantity} onChange={e=>setIngredients(ingredients.map((x,j)=>j===n?{...x,quantity:e.target.value}:x))}/><button type="button" className="col-span-1" disabled={ingredients.length===1} onClick={()=>setIngredients(ingredients.filter((_,j)=>j!==n))}><Trash2 className="w-4 h-4"/></button></div>)}<Button type="button" variant="outline" size="sm" onClick={()=>setIngredients([...ingredients,{product_id:"",quantity:"1"}])}>+ Materia prima</Button></div><div className="bg-secondary rounded-xl p-3 text-sm">Costo estimado: <strong>{fmtMoney(cost/Math.max(Number(yieldQty)||1,1),currency)} por unidad</strong></div><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving||!ingredients.some(i=>i.product_id)}>{saving?"Guardando…":"Guardar receta"}</Button></div></form></div></div>}
 </div>;
}
