import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { Camera, Check, ImagePlus, Minus, Package, Plus, Search, ShoppingCart, Trash2, WandSparkles, X } from "lucide-react";
import { toast } from "sonner";
import api,{apiError} from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { fmtBs,fmtMoney,fmtNum } from "../lib/format";

const money=(n,c)=>fmtMoney(n,c||"USD");
const autoImage=(name)=>`https://loremflickr.com/600/600/${encodeURIComponent(String(name).trim())},product/all`;

export default function Stock(){
 const {business,rate}=useAuth();const [products,setProducts]=useState([]),[search,setSearch]=useState(""),[category,setCategory]=useState("todas"),[cart,setCart]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showCart,setShowCart]=useState(false),[photoProduct,setPhotoProduct]=useState(null);const fileRef=useRef(null);const currency=business?.currency||"USD";
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/products");setProducts((r.data.products||[]).filter(p=>Number(p.stock||0)>0))}catch(e){toast.error(apiError(e))}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const categories=useMemo(()=>[...new Set(products.map(p=>p.category).filter(Boolean))],[products]);const visible=useMemo(()=>products.filter(p=>(category==="todas"||p.category===category)&&(!search||[p.name,p.sku,p.barcode].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase()))),[products,search,category]);
 const qty=id=>cart.find(x=>x.id===id)?.quantity||0;
 const add=(p)=>{if(qty(p.id)>=p.stock){toast.warning("No hay más unidades disponibles");return}setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}])};
 const remove=(id)=>setCart(c=>c.map(x=>x.id===id?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0));
 const clear=()=>setCart([]);const total=cart.reduce((s,x)=>s+x.sale_price*x.quantity,0);const count=cart.reduce((s,x)=>s+x.quantity,0);
 const setPhoto=async(p,file)=>{if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const payload={name:p.name,sku:p.sku||null,barcode:p.barcode||null,category:p.category||null,brand:p.brand||null,supplier:p.supplier||null,purchase_price:Number(p.purchase_price||0),sale_price:Number(p.sale_price||0),stock:Number(p.stock||0),min_stock:Number(p.min_stock||0),max_stock:p.max_stock??null,unit:p.unit||"unidad",image_url:String(reader.result)};await api.put(`/products/${p.id}`,payload);setProducts(ps=>ps.map(x=>x.id===p.id?{...x,image_url:payload.image_url}:x));toast.success("Foto del producto guardada")}catch(e){toast.error(apiError(e))}};reader.readAsDataURL(file)};
 const automatic=async p=>{setSaving(true);try{const image_url=autoImage(p.name);const payload={name:p.name,sku:p.sku||null,barcode:p.barcode||null,category:p.category||null,brand:p.brand||null,supplier:p.supplier||null,purchase_price:Number(p.purchase_price||0),sale_price:Number(p.sale_price||0),stock:Number(p.stock||0),min_stock:Number(p.min_stock||0),max_stock:p.max_stock??null,unit:p.unit||"unidad",image_url};await api.put(`/products/${p.id}`,payload);setProducts(ps=>ps.map(x=>x.id===p.id?{...x,image_url}:x));toast.success("Imagen relacionada asignada")}catch(e){toast.error(apiError(e))}finally{setSaving(false)}};
 const checkout=async()=>{if(!cart.length)return;setSaving(true);try{await api.post("/sales",{items:cart.map(x=>({product_id:x.id,quantity:x.quantity,unit_price:x.sale_price,discount:0})),payment_method:"efectivo",payment_parts:[]});toast.success("Venta registrada");clear();setShowCart(false);load()}catch(e){toast.error(apiError(e))}finally{setSaving(false)}};
 return <div className="space-y-5" data-testid="stock-page"><div className="flex items-center justify-between gap-3 flex-wrap"><div><h1 className="font-heading text-3xl font-extrabold tracking-tight flex items-center gap-2"><Package className="w-7 h-7 text-primary"/>Stock</h1><p className="text-sm text-muted-foreground mt-1">Selecciona productos disponibles y arma tu venta desde una sola pantalla.</p></div><button onClick={()=>setShowCart(true)} className="relative flex items-center gap-2 rounded-xl bg-primary text-white px-4 py-2.5 font-semibold shadow-sm"><ShoppingCart className="w-5 h-5"/>Carrito{count>0&&<span className="min-w-6 h-6 px-1 rounded-full bg-white text-primary text-xs flex items-center justify-center font-bold">{count}</span>}</button></div>
 <div className="flex gap-3 flex-wrap"><div className="relative flex-1 min-w-60"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto, SKU o código…" className="w-full h-11 rounded-xl border bg-card pl-10 pr-4 outline-none focus:ring-2 focus:ring-primary/20"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="h-11 rounded-xl border bg-card px-3"><option value="todas">Todas las categorías</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
 {loading?<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">{[1,2,3,4,5,6].map(i=><div key={i} className="h-72 rounded-2xl bg-secondary animate-pulse"/>)}</div>:visible.length===0?<div className="bg-card border rounded-2xl p-14 text-center"><Package className="w-12 h-12 mx-auto text-muted-foreground mb-3"/><h3 className="font-bold">No hay productos en stock</h3><p className="text-sm text-muted-foreground mt-1">Los productos aparecerán aquí cuando tengan existencias.</p></div>:<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">{visible.map(p=>{const q=qty(p.id);return <div key={p.id} className={`bg-card border rounded-2xl overflow-hidden shadow-sm transition ${q?'ring-2 ring-primary':''}`}><div className="aspect-square bg-secondary relative"><img src={p.image_url||autoImage(p.name)} alt={p.name} className="w-full h-full object-cover" onError={e=>{e.currentTarget.style.display="none";e.currentTarget.parentElement.classList.add("flex","items-center","justify-center");}}/><div className="absolute top-2 left-2 px-2 py-1 rounded-lg bg-white/90 backdrop-blur text-xs font-bold">Stock: {fmtNum(p.stock)}</div>{q>0&&<div className="absolute top-2 right-2 w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-bold">{q}</div>}</div><div className="p-3.5"><p className="font-bold truncate">{p.name}</p><p className="text-xs text-muted-foreground truncate">{p.category||"General"} · {p.sku||""}</p><div className="mt-2"><p className="font-heading font-extrabold text-lg">{money(p.sale_price,currency)}</p>{rate?.rate&&<p className="text-xs text-muted-foreground">{fmtBs(p.sale_price*rate.rate)}</p>}</div><div className="grid grid-cols-[auto_1fr_auto] gap-2 mt-3"><button title="Foto propia" onClick={()=>{setPhotoProduct(p);fileRef.current?.click()}} className="h-10 w-10 rounded-xl border flex items-center justify-center hover:bg-secondary"><Camera className="w-4 h-4"/></button><button onClick={()=>add(p)} disabled={q>=p.stock} className="h-10 rounded-xl bg-primary text-white font-bold flex items-center justify-center gap-1.5 disabled:opacity-40"><Plus className="w-4 h-4"/>Agregar</button><button title="Imagen automática" onClick={()=>automatic(p)} disabled={saving} className="h-10 w-10 rounded-xl border flex items-center justify-center hover:bg-secondary"><WandSparkles className="w-4 h-4"/></button></div>{q>0&&<div className="flex items-center justify-center gap-3 mt-2"><button onClick={()=>remove(p.id)} className="w-8 h-8 rounded-full border flex items-center justify-center"><Minus className="w-4 h-4"/></button><span className="font-bold">{q}</span><button onClick={()=>add(p)} disabled={q>=p.stock} className="w-8 h-8 rounded-full border flex items-center justify-center"><Plus className="w-4 h-4"/></button></div>}</div></div>})}</div>}
 <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{setPhoto(photoProduct,e.target.files?.[0]);e.target.value=""}}/>
 {showCart&&<div className="fixed inset-0 z-50 bg-black/40" onClick={()=>setShowCart(false)}><aside className="absolute right-0 top-0 h-full w-full max-w-md bg-background shadow-2xl flex flex-col" onClick={e=>e.stopPropagation()}><div className="p-5 border-b flex items-center gap-3"><ShoppingCart className="w-5 h-5 text-primary"/><h2 className="font-heading text-xl font-bold flex-1">Carrito</h2><button onClick={()=>setShowCart(false)}><X className="w-5 h-5"/></button></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{!cart.length?<div className="h-full flex flex-col items-center justify-center text-center text-muted-foreground"><ShoppingCart className="w-12 h-12 mb-3"/><p className="font-semibold">Tu carrito está vacío</p><p className="text-sm">Agrega productos desde el stock.</p></div>:cart.map(x=><div key={x.id} className="flex gap-3 border rounded-xl p-3"><img src={x.image_url||autoImage(x.name)} className="w-14 h-14 rounded-lg object-cover" alt=""/><div className="flex-1 min-w-0"><p className="font-semibold truncate">{x.name}</p><p className="text-sm">{money(x.sale_price,currency)} × {x.quantity}</p><div className="flex items-center gap-2 mt-1"><button onClick={()=>remove(x.id)} className="w-7 h-7 rounded-full border flex items-center justify-center"><Minus className="w-3 h-3"/></button><span className="text-sm font-bold">{x.quantity}</span><button onClick={()=>add(x)} className="w-7 h-7 rounded-full border flex items-center justify-center"><Plus className="w-3 h-3"/></button></div></div><div className="text-right font-bold">{money(x.sale_price*x.quantity,currency)}</div></div>)}</div><div className="p-5 border-t space-y-3"><div className="flex justify-between text-lg"><span>Total</span><b>{money(total,currency)}</b></div>{rate?.rate&&<div className="flex justify-between text-sm text-muted-foreground"><span>Equivalente</span><b>{fmtBs(total*rate.rate)}</b></div>}<button onClick={checkout} disabled={!cart.length||saving} className="w-full h-12 rounded-xl bg-primary text-white font-bold disabled:opacity-40 flex items-center justify-center gap-2"><Check className="w-5 h-5"/>{saving?"Registrando…":"Registrar venta"}</button><button onClick={clear} disabled={!cart.length} className="w-full h-10 rounded-xl border text-sm font-semibold disabled:opacity-40"><Trash2 className="w-4 h-4 inline mr-1"/>Vaciar carrito</button></div></aside></div>}
 </div>
}